// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf3
// Node name       : Hash File
// Node id         : b4f5669a-cffa-4214-9ccd-34ed24ae28c5
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : f28b252066258641424572308ab2697507da3d9aa6db171dc8969ae554bed212
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./hash-file');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Best effort SHA-256 over the downloaded bytes. Never blocks storage if it is unavailable.
const item = $input.first();
const base = $('Set Folder Id').first().json;
let hash = 'NOT_COMPUTED';
let size_bytes = 0;
try {
  const buf = await this.helpers.getBinaryDataBuffer(0, 'data');
  size_bytes = buf.length;
  const digest = await crypto.subtle.digest('SHA-256', buf);
  hash = Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('');
} catch (e) {
  hash = 'NOT_COMPUTED';
  try { size_bytes = Number((item.binary && item.binary.data && item.binary.data.fileSize) || 0); } catch (e2) {}
}
return [{ json: { ...base, hash, size_bytes }, binary: item.binary }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf3",
  "nodeName": "Hash File",
  "nodeId": "b4f5669a-cffa-4214-9ccd-34ed24ae28c5",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "f28b252066258641424572308ab2697507da3d9aa6db171dc8969ae554bed212"
} };
