// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf1
// Node name       : Format Status
// Node id         : 7561e30e-bbf9-49bf-aa40-b4c21621935e
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 220c01fb6f028f6f82266c12aa1b84b09e952148cbdf3ae7414e104ee9d60eca
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./format-status');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
const j = $('Resolve Route').first().json;
const rows = $input.all().map(i => i.json).filter(r => r && r.matter_id);
const wantOne = j.route === 'STATUS_REQUEST' && j.matter_ref;

function line(r) {
  return [
    r.matter_id + '  ' + (r.title || '(untitled)'),
    '  Status: ' + (r.status || 'UNKNOWN'),
    '  Playbook: ' + (r.playbook_id || 'UNASSIGNED'),
    '  Last activity: ' + (r.last_activity_at || r.updated_at || 'unknown'),
  ].join('\n');
}

if (!rows.length) {
  return [{ json: { reply: 'There are no matters on the register yet.\n\nSend a description of a legal task to open one.' } }];
}

if (wantOne) {
  const hit = rows.filter(r => String(r.matter_id).toUpperCase() === String(j.matter_ref).toUpperCase());
  if (!hit.length) {
    return [{ json: { reply: 'I have no matter with the id ' + j.matter_ref + '.\n\nSend /matters to list the open matters.' } }];
  }
  const r = hit[hit.length - 1];
  let missing = [];
  try { missing = JSON.parse(r.missing_facts_json || '[]'); } catch (e) { missing = []; }
  let risks = [];
  try { risks = JSON.parse(r.risk_flags_json || '[]'); } catch (e) { risks = []; }
  const body = [
    line(r),
    '',
    'Missing information: ' + (missing.length ? '\n- ' + missing.join('\n- ') : 'none recorded'),
    'Risk flags: ' + (risks.length ? risks.join(', ') : 'none recorded'),
  ].join('\n');
  return [{ json: { reply: body } }];
}

const open = rows.filter(r => !['CLOSED','REJECTED'].includes(String(r.status || '').toUpperCase()));
const body = 'Open matters (' + open.length + ')\n\n' + open.map(line).join('\n\n');
return [{ json: { reply: body.slice(0, 3800) } }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf1",
  "nodeName": "Format Status",
  "nodeId": "7561e30e-bbf9-49bf-aa40-b4c21621935e",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "220c01fb6f028f6f82266c12aa1b84b09e952148cbdf3ae7414e104ee9d60eca"
} };
