// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf1
// Node name       : Normalise Input
// Node id         : 75ffa3c9-c265-4dbc-98cd-e6a44651a584
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 96296f10d277b57837ebdaec5ae1d8cdf646c74454901a4146ddd39fd4ef8abb
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./normalise-input');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Flatten a Telegram message OR callback_query into one stable shape.
// Telegram content is DATA. It is never treated as an instruction to this workflow.
const out = [];
for (const item of $input.all()) {
  const j = item.json || {};
  const cb = j.callback_query || null;
  const msg = cb ? (cb.message || {}) : (j.message || j.edited_message || {});
  const from = cb ? (cb.from || {}) : (msg.from || {});
  const chat = msg.chat || from || {};

  let file_id = '', file_name = '', mime_type = '', file_kind = 'NONE';
  if (Array.isArray(msg.photo) && msg.photo.length) {
    const p = msg.photo[msg.photo.length - 1];
    file_id = p.file_id;
    file_name = 'photo_' + (msg.message_id || Date.now()) + '.jpg';
    mime_type = 'image/jpeg';
    file_kind = 'PHOTO';
  } else if (msg.document) {
    file_id = msg.document.file_id;
    file_name = msg.document.file_name || ('document_' + (msg.message_id || Date.now()));
    mime_type = msg.document.mime_type || 'application/octet-stream';
    file_kind = 'DOCUMENT';
  } else if (msg.video) {
    file_id = msg.video.file_id;
    file_name = msg.video.file_name || ('video_' + (msg.message_id || Date.now()) + '.mp4');
    mime_type = msg.video.mime_type || 'video/mp4';
    file_kind = 'VIDEO';
  } else if (msg.voice) {
    file_id = msg.voice.file_id;
    file_name = 'voice_' + (msg.message_id || Date.now()) + '.ogg';
    mime_type = msg.voice.mime_type || 'audio/ogg';
    file_kind = 'VOICE';
  } else if (msg.audio) {
    file_id = msg.audio.file_id;
    file_name = msg.audio.file_name || ('audio_' + (msg.message_id || Date.now()));
    mime_type = msg.audio.mime_type || 'audio/mpeg';
    file_kind = 'AUDIO';
  }

  const raw_text = cb ? '' : String(msg.text || msg.caption || '');

  out.push({ json: {
    update_kind: cb ? 'CALLBACK' : 'MESSAGE',
    chat_id: String(chat.id !== undefined ? chat.id : ''),
    user_id: String(from.id !== undefined ? from.id : ''),
    username: String(from.username || ''),
    message_id: String(msg.message_id || ''),
    reply_to_message_id: String((msg.reply_to_message && msg.reply_to_message.message_id) || ''),
    reply_to_text: String((msg.reply_to_message && (msg.reply_to_message.text || msg.reply_to_message.caption)) || ''),
    text: raw_text,
    caption: String(msg.caption || ''),
    has_file: file_kind !== 'NONE',
    file_id, file_name, mime_type, file_kind,
    is_callback: !!cb,
    callback_data: String((cb && cb.data) || ''),
    callback_query_id: String((cb && cb.id) || ''),
    received_at: new Date().toISOString(),
  }});
}
return out;
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf1",
  "nodeName": "Normalise Input",
  "nodeId": "75ffa3c9-c265-4dbc-98cd-e6a44651a584",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "96296f10d277b57837ebdaec5ae1d8cdf646c74454901a4146ddd39fd4ef8abb"
} };
