// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf1
// Node name       : Parse Command
// Node id         : 1d16630b-1467-4cef-b59b-5b0d710503fa
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 775d630a5f3ae0d39180ac5893cb68b18291af4372fe42755a360d7610711741
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./parse-command');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Deterministic first pass. The LLM is only used when this cannot decide.
const inp = $('Normalise Input').first().json;
const sessRows = $input.all().map(i => i.json).filter(r => r && r.chat_id);
const sess = sessRows.length ? sessRows[sessRows.length - 1] : {};

const text = String(inp.text || '').trim();
const cbData = String(inp.callback_data || '');

const base = {
  ...inp,
  session_matter_id: String(sess.active_matter_id || ''),
  session_awaiting: String(sess.awaiting || ''),
  session_awaiting_ref: String(sess.awaiting_ref || ''),
  route: '',
  matter_ref: '',
  approval_id: '',
  decision: '',
  draft_ref: '',
  payload_text: text,
  needs_llm: false,
  deterministic: true,
  // Only /proceed sets this. WF2's Finalise Plan reads it to record still-missing
  // required facts as unobtainable instead of asking about them forever.
  force_proceed: false,
};

// 1. Inline-button callback: "A|APR-xxxx|APPROVE"
if (cbData) {
  const parts = cbData.split('|');
  if (parts[0] === 'A' && parts[1]) {
    base.route = 'APPROVAL_DECISION';
    base.approval_id = parts[1];
    base.decision = (parts[2] || 'APPROVE').toUpperCase();
    return [{ json: base }];
  }
  base.route = 'AMBIGUOUS';
  return [{ json: base }];
}

// 2. Explicit approval words with a token
const apr = text.match(/^\/?(APPROVE_LINK|APPROVE|REJECT|REQUEST_EDIT|REQUEST_MORE_INFORMATION)\s+(APR-[A-Za-z0-9-]+)\s*([\s\S]*)$/i);
if (apr) {
  base.route = 'APPROVAL_DECISION';
  base.decision = apr[1].toUpperCase();
  base.approval_id = apr[2].toUpperCase();
  base.payload_text = (apr[3] || '').trim();
  return [{ json: base }];
}

// 3. Slash commands
const cmd = text.match(/^\/([a-z-]+)\s*([\s\S]*)$/i);
if (cmd) {
  const c = cmd[1].toLowerCase();
  const rest = (cmd[2] || '').trim();
  base.payload_text = rest;
  const map = {
    'new': 'NEW_MATTER',
    'dryrun': 'HELP',
    'status': 'STATUS_REQUEST',
    'matters': 'LIST_MATTERS',
    // B5a: /draft asks for the FIRST draft of the next open drafting action.
    // /edit revises a draft that already exists. Both land in the DRAFT group,
    // but keeping them as distinct routes makes the Events log readable.
    'draft': 'DRAFT_REQUEST',
    'edit': 'DRAFT_EDIT',
    // /proceed is a continuation, so Resolve Matter reuses the existing matter
    // rather than opening a new one.
    'proceed': 'CONTINUE_MATTER',
    'add-evidence': 'EVIDENCE_UPLOAD',
    'followup': 'FOLLOW_UP_REQUEST',
    'help': 'HELP',
    'start': 'HELP',
  };
  if (map[c]) {
    base.route = map[c];
    if (c === 'proceed') {
      base.force_proceed = true;
      // The planner is told plainly what the owner has accepted, so the summary it
      // writes matches what actually happened.
      base.payload_text = 'The owner confirms that the remaining required facts are not available. '
        + 'Proceed with the plan and record those facts as unobtainable. ' + rest;
    }
    const dref = rest.match(/\b(DRF-[A-Za-z0-9-]+)\b/i);
    if (dref) base.draft_ref = dref[1].toUpperCase();
    const mref = rest.match(/\b(MAT-[A-Za-z0-9-]+)\b/i);
    if (mref) base.matter_ref = mref[1].toUpperCase();
    // A NEW_MATTER must not inherit the active matter. Every other command is a
    // continuation or a lookup, so the session fallback still applies to them.
    if (!base.matter_ref && base.route !== 'NEW_MATTER') base.matter_ref = base.session_matter_id;
    return [{ json: base }];
  }
  base.route = 'AMBIGUOUS';
  return [{ json: base }];
}

// 4. A file with no command is an evidence upload
if (inp.has_file) {
  base.route = 'EVIDENCE_UPLOAD';
  const mref = (text + ' ' + String(inp.reply_to_text || '')).match(/\b(MAT-[A-Za-z0-9-]+)\b/i);
  base.matter_ref = mref ? mref[1].toUpperCase() : base.session_matter_id;
  return [{ json: base }];
}

// 5. Empty message
if (!text) {
  base.route = 'AMBIGUOUS';
  return [{ json: base }];
}

// 5.5  Active matter awaiting information - deterministic continuation.
//      Fires only for plain free text when the session has an open
//      NEEDS_INFORMATION matter. Slash commands are resolved at step 3
//      so /new still creates a new matter regardless of awaiting state.
if (base.session_awaiting === 'NEEDS_INFORMATION' && base.session_matter_id) {
  base.route = 'CONTINUE_MATTER';
  base.matter_ref = base.session_matter_id;
  base.needs_llm = false;
  base.deterministic = true;
  return [{ json: base }];
}

// 6. Everything else goes to the classifier
const mref = (text + ' ' + String(inp.reply_to_text || '')).match(/\b(MAT-[A-Za-z0-9-]+)\b/i);
if (mref) base.matter_ref = mref[1].toUpperCase();
const dref = (text + ' ' + String(inp.reply_to_text || '')).match(/\b(DRF-[A-Za-z0-9-]+)\b/i);
if (dref) base.draft_ref = dref[1].toUpperCase();
base.needs_llm = true;
base.deterministic = false;
return [{ json: base }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf1",
  "nodeName": "Parse Command",
  "nodeId": "1d16630b-1467-4cef-b59b-5b0d710503fa",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "775d630a5f3ae0d39180ac5893cb68b18291af4372fe42755a360d7610711741"
} };
