// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf1
// Node name       : Resolve Route
// Node id         : f6557dbb-b74d-41b6-8106-a4bbcc96d4c7
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : d079c9a96c6f90554ff9161fb4a9a04e03c2bc6eb4d5d2077aa4ac4045837730
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./resolve-route');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
const j = $input.first().json;
const r = String(j.route || 'AMBIGUOUS');
const group = ({
  NEW_MATTER: 'PLAN',
  CONTINUE_MATTER: 'PLAN',
  CLARIFICATION_ANSWER: 'PLAN',
  FOLLOW_UP_REQUEST: 'PLAN',
  EVIDENCE_NOTE: 'PLAN',
  // B5a: an explicit request for a first draft, distinct from revising one.
  DRAFT_REQUEST: 'DRAFT',
  DRAFT_EDIT: 'DRAFT',
  APPROVAL_DECISION: 'APPROVAL',
  EVIDENCE_UPLOAD: 'EVIDENCE',
  STATUS_REQUEST: 'STATUS',
  LIST_MATTERS: 'STATUS',
  HELP: 'HELP',
  AMBIGUOUS: 'CLARIFY',
  CLASSIFIER_FAILED: 'CLARIFY',
})[r] || 'CLARIFY';

return [{ json: { ...j, route: r, route_group: group } }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf1",
  "nodeName": "Resolve Route",
  "nodeId": "f6557dbb-b74d-41b6-8106-a4bbcc96d4c7",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "d079c9a96c6f90554ff9161fb4a9a04e03c2bc6eb4d5d2077aa4ac4045837730"
} };
