// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf2
// Node name       : Expand Actions
// Node id         : 62cfb096-89cd-457f-8fa1-edd05375881a
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : d88a70418dd6e220b2753045dc2017752e9a0778d01dce9f09f9ee84603ebb9d
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./expand-actions');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Reads Finalise Plan, not Validate Plan JSON: the action ids are rewritten there
// with a per-plan stamp so they are unique forever.
const p = $('Finalise Plan').first().json;
return (p.actions || []).map(a => ({ json: a }));
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf2",
  "nodeName": "Expand Actions",
  "nodeId": "62cfb096-89cd-457f-8fa1-edd05375881a",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "d88a70418dd6e220b2753045dc2017752e9a0778d01dce9f09f9ee84603ebb9d"
} };
