// AUTO-GENERATED by .tooling/extract-units.py — MANUALLY MODIFIED on 2026-08-25.
// Source workflow : wf2
// Node name       : Finalise Plan
// Node id         : 7a18e9d1-820c-4aa7-a84b-bab52f95bf74
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 6de482a68e8c04ff9aa624a0a98a0e7875246fa06c5ea93cd4f2a33bb6c753ad
//
// CHANGE D-TESTFLAG-01 (2026-08-25): Deterministic test-data stamp.
// Base: active WF2 Finalise Plan (sha256 3d9e63e9..., 13381 bytes).
// Applied only: stamp block inserted between noteText and const common.
// Regex tightened to require delimiter: /^MAT-(?:TEST|QA|SANDBOX)(?:[_-]|$)/i
// All active behaviour preserved: B1 risk flags, plan stamp format (P+seconds+base36),
// action ID prefix format (MAT-→ACT-, hyphens preserved).
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./finalise-plan');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Sits between Plan Valid? and Upsert Matter. Deterministic controls that must not
// depend on the prompt holding, and that avoid touching Validate Plan JSON and its
// 20KB of playbook definitions.
//
// 1. REQUIRED vs OPTIONAL. Validate Plan JSON gates on
//    `raw.requires_information || missing.length > 0`, with no distinction between a
//    required fact and an optional one. Observed live: a matter reached CLASSIFIED,
//    then dropped back to NEEDS_INFORMATION over repair_quote_amount and
//    prior_communications, both optional_facts. Only missing REQUIRED facts gate now.
//
// 2. CONTRADICTION CONTROL. Validate Plan JSON seeds its missing list from the model's
//    own raw.missing_facts and never prunes a key that IS present in facts, so a fact
//    could be reported known and missing at once. Recorded facts win, the plan
//    proceeds, and the contradiction is made loud.
//
// 3. /proceed. A required fact can be genuinely unobtainable. Recorded as
//    UNOBTAINABLE_OWNER_CONFIRMED: an owner declaration, not a verified finding.
//
// 4. QUESTION HYGIENE. Duplicate and mangled questions removed.
//
// 5. IMMUTABLE ACTION IDS. Validate Plan JSON mints ids purely positionally
//    (ACT-<matter>-003), so a re-plan reuses the same id for a different action. That
//    made ids non-unique, and my earlier upsert-on-position fix was worse: it silently
//    OVERWROTE the old row, changing what ACT-...-003 meant while Drafts and Approvals
//    rows still referenced it. Ids now carry a per-plan stamp, so an id is unique
//    forever, and depends_on is remapped in the same pass so a dependency can never
//    resolve against an action belonging to a different plan. Nothing is overwritten
//    or deleted: readers pick the newest stamp per matter, and history stays intact.

const p = $input.first().json;
if (!p.plan_valid) return [{ json: p }];

const base = $('Resolve Matter').first().json;
const force = base.force_proceed === true || String(base.force_proceed).toLowerCase() === 'true';

function parse(s, fallback) { try { return JSON.parse(s); } catch (e) { return fallback; } }
const isKey = v => /^[a-z][a-z0-9_]*$/.test(String(v));

const pbAll = ($('Playbook Library').first().json || {}).playbooks || {};
const pb = pbAll[p.playbook_id] || {};
const REQUIRED = (pb.required_facts || []).map(String);
const OPTIONAL = (pb.optional_facts || []).map(String);

const PLACEHOLDER = /^(UNKNOWN|MISSING|UNOBTAINABLE|UNOBTAINABLE_OWNER_CONFIRMED|N\/A|NA|NONE|TBC|TBD|PENDING|)$/i;
function hasRealValue(v) {
  const s = String(v === null || v === undefined ? '' : v).trim();
  return !!s && !PLACEHOLDER.test(s);
}

const facts = parse(p.facts_json, {});
let missing = parse(p.missing_facts_json, []);

// --- 2. contradiction control ----------------------------------------------
const contradictions = missing.filter(m => isKey(m) && hasRealValue(facts[m]));
if (contradictions.length) missing = missing.filter(m => !contradictions.includes(m));

// --- 2b. FACT-KEY VOCABULARY (B1) ------------------------------------------
// Observed on MAT-20260101-006: own_vehicle_registration was reported missing while
// registration = "9XYZ876" sat in the same facts object. Two more of the same on that
// matter: incident_datetime missing beside incident_date + incident_time, and
// damage_description missing beside damage.
//
// Mechanism. Validate Plan JSON marks a required fact missing with
// hasOwnProperty(facts, rf). The planner had written the value under a key of its own
// choosing, so the canonical key is absent and the fact is reported missing although the
// owner did state it. Classify and Plan rule 11 already forbids inventing key names, but
// rule 11 lived only in the prompt: Validate Plan JSON accepts any key into facts, and the
// existing UNKNOWN_FACT_KEYS check inspects only the MISSING list, never the facts side.
// The contradiction control immediately above cannot see this class of fault either,
// because it compares by identical key and facts['own_vehicle_registration'] is undefined.
//
// This closes the gap on the facts side. Three deliberate choices:
//
//   NO MAPPING. registration is not silently bound to own_vehicle_registration. Nothing in
//   the record says whether 9XYZ876 is the owner's vehicle or another party's, and binding
//   a guessed value to a legal fact is worse than reporting the gap. An alias table would
//   make that guess systematic.
//
//   NOTHING IS DISCARDED. Off-vocabulary keys stay exactly where they are in facts_json,
//   under their original names, so no owner-stated fact is lost and the drafter keeps
//   seeing them. unmapped_facts_json is an audit copy, not a relocation.
//
//   IT IS LOUD. UNKNOWN_FACT_KEYS and human review are raised. When an off-vocabulary key
//   coexists with a missing REQUIRED fact, REQUIRED_FACT_MAY_BE_MISKEYED is raised too:
//   that is the combination that produced the false gap, and it is the one a human must
//   look at. Both ride on risk_flags_json, which is a real Matters column. So does
//   unmapped_facts_json now: Matters column N, added 2026-08-21, and written by Upsert
//   Matter. That column carries the audit copy, and it exists for audit and human review.
//   The original off-vocabulary key is NOT moved: it stays in facts_json under the name the
//   planner used. This is a preservation copy, not a relocation.
const VOCAB = new Set([...REQUIRED, ...OPTIONAL]);
// Routing and control values are written into facts by upstream nodes, not by the planner.
// They are not claims about the matter, so they are not off-vocabulary facts.
const CONTROL = new Set(['matter_id', 'route', 'is_new_matter', 'dry_run', 'test_data_only',
  'force_proceed', 'owner_chat_id', 'jurisdiction']);
const unmappedFacts = {};
for (const k of Object.keys(facts)) {
  if (VOCAB.has(k) || CONTROL.has(k)) continue;
  if (!hasRealValue(facts[k])) continue;
  unmappedFacts[k] = facts[k];
}
const unmappedKeys = Object.keys(unmappedFacts);

// --- 1. split the missing list --------------------------------------------
const keyish = missing.filter(isKey);
const missingRequired = keyish.filter(m => REQUIRED.includes(m));
const missingOptional = keyish.filter(m => OPTIONAL.includes(m));
const unknownKeys = keyish.filter(m => !REQUIRED.includes(m) && !OPTIONAL.includes(m));

let risks = parse(p.risk_flags_json, []);
let needsReview = p.requires_human_review === true;
let requiresInfo = missingRequired.length > 0;

if (contradictions.length) { risks.push('PLANNER_CONTRADICTION'); needsReview = true; }
if (unknownKeys.length)    { risks.push('UNKNOWN_FACT_KEYS');     needsReview = true; }
if (unmappedKeys.length)   { risks.push('UNKNOWN_FACT_KEYS');     needsReview = true; }
// The dangerous combination: a required fact is reported missing while the record holds
// facts under names this playbook does not define. One of them may BE the missing fact.
if (unmappedKeys.length && missingRequired.length) {
  risks.push('REQUIRED_FACT_MAY_BE_MISKEYED');
  needsReview = true;
}
if (!missingRequired.length) risks = risks.filter(r => String(r) !== 'MATERIAL_FACTS_MISSING');
if (missingOptional.length && !requiresInfo) risks.push('OPTIONAL_FACTS_OUTSTANDING');

// --- 5. immutable, plan-stamped action ids --------------------------------
// Base36 epoch seconds sorts correctly when parsed back with parseInt(s, 36), which is
// how readers rank plans. Six characters until well past 2059.
const planStamp = 'P' + Math.floor(Date.now() / 1000).toString(36).toUpperCase();
const idPrefix = String(p.matter_id || base.matter_id || '').replace('MAT-', 'ACT-');
const srcActions = Array.isArray(p.actions) ? p.actions : [];
const idMap = {};
srcActions.forEach((a, i) => {
  idMap[String(a.action_id)] = idPrefix + '-' + planStamp + '-' + String(i + 1).padStart(3, '0');
});
const actions = srcActions.map((a, i) => {
  const seq = String(i + 1).padStart(3, '0');
  const deps = parse(a.depends_on_json, []);
  return { ...a,
    action_id: idMap[String(a.action_id)],
    // Remapped so a dependency can never point at an action from an earlier plan.
    depends_on_json: JSON.stringify(deps.map(d => idMap[String(d)] || String(d))),
    idempotency_key: String(p.matter_id) + '|' + planStamp + '|' + seq,
  };
});

// --- 4. question hygiene ---------------------------------------------------
const STOP = new Set(['about','after','anyone','their','there','these','those','which','whether',
  'would','could','should','have','with','from','your','what','does','been','this','that','they',
  'into','else','also','send','then','than','will','when','were','and','the','you','for','any',
  'has','had','not','are','was','its','our']);
function sig(q) {
  return new Set(String(q).toLowerCase().replace(/[^a-z0-9 ]/g, ' ').split(/\s+/)
    .filter(w => w.length >= 5 && !STOP.has(w)));
}
function overlap(a, b) { let n = 0; for (const w of a) if (b.has(w)) n++; return n; }

const cleaned = [];
for (const q of (p.questions || [])) {
  let t = String(q || '').trim();
  if (!t) continue;
  const m = t.match(/^What is the (.+)\?$/);
  if (m && /\s/.test(m[1]) && m[1].length > 30) t = m[1].trim();
  if (!/[?.]$/.test(t)) t += '?';
  cleaned.push(t.charAt(0).toUpperCase() + t.slice(1));
}
const kept = [];
for (const q of [...cleaned].sort((a, b) => b.length - a.length)) {
  const s = sig(q);
  if (kept.some(k => overlap(s, sig(k)) >= 2)) continue;
  kept.push(q);
}
const questions = cleaned.filter(q => kept.includes(q)).slice(0, 10);

const notes = []
  .concat(contradictions.length
    ? ['The planner listed ' + contradictions.length + ' fact(s) as missing while also recording a value for them ('
       + contradictions.join(', ') + '). I kept the recorded values and flagged the matter for review.'] : [])
  .concat(unknownKeys.length
    ? ['The planner used ' + unknownKeys.length + ' fact key(s) that are not in this playbook ('
       + unknownKeys.join(', ') + '). They are not blocking the matter.'] : [])
  .concat(unmappedKeys.length
    ? ['I recorded ' + unmappedKeys.length + ' fact(s) under names this playbook does not define: '
       + unmappedKeys.join(', ') + '. I kept them exactly as recorded and I did not rename them.'] : [])
  .concat((unmappedKeys.length && missingRequired.length)
    ? ['One of those may be a required fact under the wrong name. Required and still missing: '
       + missingRequired.join(', ') + '. I will not assume which is which, so please confirm.'] : [])
  .concat((missingOptional.length && !requiresInfo)
    ? ['Optional details still outstanding, not blocking: ' + missingOptional.join(', ') + '.'] : []);
const noteText = notes.length ? ' ' + notes.join(' ') : '';

// D-TESTFLAG-01 (2026-08-25): Deterministic test-data stamp.
// The CONTROL set above reserves test_data_only as a system-injected field.
// No upstream node writes it; this stamps it for every matter whose matter_id
// matches a canonical test prefix. The delimiter requirement (hyphen, underscore,
// or end-of-string) prevents false matches such as MAT-TESTVALUE or MAT-SANDBOXPRO.
// String 'true' (not boolean) matches the truthy read in WF5 isTestMatter.
// Fail-closed: a blank or missing matter_id matches no prefix and receives no stamp,
// so a matter with an unrecognisable id is treated as production (conservative).
const _TEST_ID_RE = /^MAT-(?:TEST|QA|SANDBOX)(?:[_-]|$)/i;
if (_TEST_ID_RE.test(String(p.matter_id || '').trim())) {
  facts.test_data_only = 'true';
}

const common = {
  ...p,
  actions,
  plan_stamp: planStamp,
  facts_json: JSON.stringify(facts),
  missing_facts_json: JSON.stringify(missingRequired),
  optional_missing_facts_json: JSON.stringify(missingOptional),
  unknown_fact_keys_json: JSON.stringify(unknownKeys),
  unmapped_facts_json: JSON.stringify(unmappedFacts),
  unmapped_fact_keys_json: JSON.stringify(unmappedKeys),
  planner_contradictions_json: JSON.stringify(contradictions),
};

if (!force) {
  return [{ json: { ...common,
    risk_flags_json: JSON.stringify(Array.from(new Set(risks))),
    requires_information: requiresInfo,
    requires_human_review: needsReview,
    matter_status: requiresInfo ? 'NEEDS_INFORMATION' : 'CLASSIFIED',
    questions: requiresInfo ? questions : [],
    owner_summary: String(p.owner_summary || '') + noteText,
    proceed_hint: requiresInfo
      ? 'If you cannot get a fact, send /proceed ' + p.matter_id
        + ' and I will record it as unobtainable and carry on. The gap stays on the record.'
      : '',
  }}];
}

// --- 3. forced proceed -----------------------------------------------------
const unobtainable = [];
for (const m of missingRequired) {
  if (hasRealValue(facts[m])) continue;
  facts[m] = 'UNOBTAINABLE_OWNER_CONFIRMED';
  unobtainable.push(m);
}

risks = risks.filter(r => String(r) !== 'MATERIAL_FACTS_MISSING');
if (unobtainable.length) risks.push('REQUIRED_FACTS_UNOBTAINABLE');
// /proceed records a missing required fact as an owner declaration of unobtainability.
// If the record also holds off-vocabulary facts, one of them may be the very fact just
// declared unobtainable. The declaration is the owner's to make, so it is not blocked,
// but it must not pass quietly.
if (unmappedKeys.length && unobtainable.length) risks.push('REQUIRED_FACT_MAY_BE_MISKEYED');
risks.push('REQUIRES_HUMAN_REVIEW');

return [{ json: { ...common,
  facts_json: JSON.stringify(facts),
  missing_facts_json: JSON.stringify([]),
  unobtainable_facts_json: JSON.stringify(unobtainable),
  risk_flags_json: JSON.stringify(Array.from(new Set(risks))),
  requires_information: false,
  requires_human_review: true,
  matter_status: 'CLASSIFIED',
  questions: [],
  forced_proceed: true,
  owner_summary: String(p.owner_summary || '')
    + (unobtainable.length
        ? ' You asked me to proceed without ' + unobtainable.length
          + ' required fact(s) that you cannot get: ' + unobtainable.join(', ')
          + '. I record them as your declaration. They are unobtainable facts, not verified findings. Every document shows the gap.'
        : ' You asked me to proceed. All required facts are present. I marked nothing as unobtainable.')
    + noteText,
}}];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf2",
  "nodeName": "Finalise Plan",
  "nodeId": "7a18e9d1-820c-4aa7-a84b-bab52f95bf74",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "6de482a68e8c04ff9aa624a0a98a0e7875246fa06c5ea93cd4f2a33bb6c753ad"
} };
