// AUTO-GENERATED by .tooling/extract-units.py — MANUALLY MODIFIED on 2026-08-25.
// Source workflow : wf2
// Node name       : Finalise Plan
// Node id         : 7a18e9d1-820c-4aa7-a84b-bab52f95bf74
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : d447a3340650f1a4fb986793d51347c6af598b10a624b1ec1988f082f9ff04e1
//
// CHANGE D-TESTFLAG-01 (2026-08-25): Added deterministic test-data stamp.
// Inserted between noteText and const common: a regex on matter_id
// (^MAT-(?:TEST|QA|SANDBOX)/i) stamps facts.test_data_only = 'true' for
// matching matters. The CONTROL set already reserved test_data_only as
// system-injected; this is the missing writer. No other key is touched.
// WF5 isTestMatter already reads facts.test_data_only — no WF5 change needed.
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./finalise-plan');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Sits between Plan Valid? and Upsert Matter. Deterministic controls that must not
// depend on the prompt holding, and that avoid touching Validate Plan JSON and its
// 20KB of playbook definitions.
//
// 1. REQUIRED vs OPTIONAL. Validate Plan JSON gates on
//    `raw.requires_information || missing.length > 0` with no distinction between
//    a required fact and an optional one. Observed live on MAT-20260819-003:
//    repair_quote_amount and prior_communications, both OPTIONAL, drove
//    requires_information = true and dropped the matter back to NEEDS_INFORMATION.
//    This node narrows: only missing REQUIRED facts gate the matter.
//
// 2. CONTRADICTION CONTROL. Validate Plan JSON seeds its missing list from the model's
//    output. The model can mark a fact missing while a value for it already sits in
//    facts_json (e.g. own_vehicle_registration listed missing even though
//    registration: 9XYZ876 was already in facts). This node removes a key from missing
//    if facts already holds a real value for it, and records the contradiction so it
//    is visible in the audit trail.
//
// 3. FACT-KEY VOCABULARY (B1). Validate Plan JSON accepts any key the model emits
//    into facts. Off-vocabulary keys are copied to unmapped_facts_json, which is an
//    audit copy only. The original key stays in facts_json exactly as the model wrote
//    it, so a future edit that renames or drops a playbook key does not silently lose
//    data that was keyed under the old name. The UNKNOWN_FACT_KEYS risk flag marks the
//    matter for human review.

'use strict';
const S = v => String(v === null || v === undefined ? '' : v).trim();
function parse(s, def) { try { const r = JSON.parse(s); return r !== null && r !== undefined ? r : def; } catch(e) { return def; } }
function isKey(s) { return /^[a-z][a-z0-9_]*$/.test(String(s)); }
function eq(a, b) { return JSON.stringify(a) === JSON.stringify(b); }

const p = $input.first().json;
const pbAll = ($('Playbook Library').first().json || {}).playbooks || {};
const pb = pbAll[p.playbook_id] || {};
const REQUIRED = (pb.required_facts || []).map(String);
const OPTIONAL = (pb.optional_facts || []).map(String);

const PLACEHOLDER = /^(UNKNOWN|MISSING|UNOBTAINABLE|UNOBTAINABLE_OWNER_CONFIRMED|N\/A|NA|NONE|TBC|TBD|PENDING|)$/i;
function hasRealValue(v) {
  const s = String(v === null || v === undefined ? '' : v).trim();
  return !!s && !PLACEHOLDER.test(s);
}

const facts = parse(p.facts_json, {});
let missing = parse(p.missing_facts_json, []);

// --- 2. contradiction control ----------------------------------------------
const contradictions = missing.filter(m => isKey(m) && hasRealValue(facts[m]));
if (contradictions.length) missing = missing.filter(m => !contradictions.includes(m));

// --- 2b. FACT-KEY VOCABULARY (B1) ------------------------------------------
// Observed on MAT-20260101-006: own_vehicle_registration was reported missing while
// registration = "9XYZ876" sat in the same facts object. Two more of the same on that
// matter: incident_datetime missing beside incident_date + incident_time, and
// damage_description missing beside damage.
//
// Mechanism. Validate Plan JSON marks a required fact missing with
// hasOwnProperty(facts, rf). The planner had written the value under a key of its own
// choosing, so the canonical key is absent and the fact is reported missing although the
// owner did state it. Classify and Plan rule 11 already forbids inventing key names, but
// rule 11 lived only in the prompt: Validate Plan JSON accepts any key into facts, and the
// existing UNKNOWN_FACT_KEYS check inspects only the MISSING list, never the facts side.
// The contradiction control immediately above cannot see this class of fault either,
// because it compares by identical key and facts['own_vehicle_registration'] is undefined.

// unmapped_facts_json: all keys in facts that are not in the playbook's vocabulary AND
// not in the CONTROL set. These are copied here for audit; the original keys remain in
// facts_json. unmapped_facts_json is an audit copy, not a relocation.
//   What the planner did: it wrote a value under a key that is not in the playbook.
//   What the audit copy does: it makes the off-vocabulary key visible to a reviewer
//   without moving or destroying the data.
//   unmapped_fact_keys_json: the list of off-vocabulary key names, for quick inspection.
//   UNKNOWN_FACT_KEYS risk flag: human review is always required when off-vocabulary keys
//   exist, because one of them might be a required fact under the wrong name.
//   unmapped_facts_json now: Matters column N, added 2026-08-21, and written by Upsert
//   Matter. Downstream nodes read it from there.
//   The original off-vocabulary key is NOT moved: it stays in facts_json under the name the
//   planner used. This is a preservation copy, not a relocation.
const VOCAB = new Set([...REQUIRED, ...OPTIONAL]);
// Routing and control values are written into facts by upstream nodes, not by the planner.
// They are not claims about the matter, so they are not off-vocabulary facts.
const CONTROL = new Set(['matter_id', 'route', 'is_new_matter', 'dry_run', 'test_data_only',
  'force_proceed', 'owner_chat_id', 'jurisdiction']);
const unmappedFacts = {};
for (const k of Object.keys(facts)) {
  if (VOCAB.has(k) || CONTROL.has(k)) continue;
  if (!hasRealValue(facts[k])) continue;
  unmappedFacts[k] = facts[k];
}
const unmappedKeys = Object.keys(unmappedFacts);

// --- 1. split the missing list --------------------------------------------
const keyish = missing.filter(isKey);
const missingRequired = keyish.filter(m => REQUIRED.includes(m));
const missingOptional = keyish.filter(m => OPTIONAL.includes(m));
const unknownKeys = keyish.filter(m => !REQUIRED.includes(m) && !OPTIONAL.includes(m));

let risks = parse(p.risk_flags_json, []);
let needsReview = p.requires_human_review === true;
let requiresInfo = missingRequired.length > 0;

if (contradictions.length) { risks.push('PLANNER_CONTRADICTION'); needsReview = true; }
if (unknownKeys.length)    { risks.push('UNKNOWN_FACT_KEYS');     needsReview = true; }

if (!requiresInfo) {
  risks = risks.filter(r => String(r) !== 'MATERIAL_FACTS_MISSING');
  if (missingOptional.length) risks.push('OPTIONAL_FACTS_OUTSTANDING');
}

// Action id stamping + depends_on remapping.
// Each run of Finalise Plan produces a unique plan-stamp so action IDs minted in this
// run are distinguishable from those minted in a prior run for the same matter.
// Format: MAT-{matterId}-P{base36stamp}-{1-based-index}.
const planStamp = Date.now().toString(36).toUpperCase();
const base = $('Resolve Matter').first().json;
const force = base.force_proceed === true || String(base.force_proceed).toLowerCase() === 'true';

const rawActions = parse(p.actions, []);
const idMap = {}; // old positional id → new stamped id
const actions = rawActions.map((a, idx) => {
  const pos = String(idx + 1);
  const newId = 'ACT-' + (S(p.matter_id) || 'UNK').replace(/[^A-Z0-9]/gi,'').toUpperCase()
    + '-P' + planStamp + '-' + pos.padStart(3, '0');
  idMap[pos] = newId;
  idMap[String(a.action_id)] = newId;
  return { ...a, action_id: newId };
});

// Remap depends_on values to the new stamped ids.
for (const a of actions) {
  let deps = parse(a.depends_on_json, []);
  deps = deps.map(d => idMap[String(d)] || String(d));
  a.depends_on_json = JSON.stringify(deps);
  a.idempotency_key = a.action_id;
  a.matter_id = S(p.matter_id);
  a.created_at = new Date().toISOString();
  a.updated_at = new Date().toISOString();
  a.status = S(a.status) || 'PENDING';
  a.draft_id = '';
  a.approval_id = '';
  a.due_at = S(a.due_at);
  a.deadline_basis = S(a.deadline_basis);
  a.blocked_reason = '';
}

const questions = (p.questions || []).map(String).filter(Boolean);

// Deduplicate questions by normalised signature.
const seen = new Set();
const deduped = questions.filter(q => {
  const sig = q.toLowerCase().replace(/[^a-z0-9 ]/g, '').split(/\s+/).filter(w => w.length >= 5).sort().join(' ');
  if (seen.has(sig)) return false;
  seen.add(sig); return true;
});

// Notes: appended to owner_summary for non-blocking observations.
const notes = []
  .concat(contradictions.length
    ? ['I found ' + contradictions.length + ' fact(s) listed as missing that are already recorded ('
+ contradictions.join(', ') + '). I kept the recorded values and flagged the matter for review.'] : [])
  .concat(unknownKeys.length
    ? ['The planner used ' + unknownKeys.length + ' fact key(s) that are not in this playbook ('
       + unknownKeys.join(', ') + '). They are not blocking the matter.'] : [])
  .concat(unmappedKeys.length
    ? ['I recorded ' + unmappedKeys.length + ' fact(s) under names this playbook does not define: '
       + unmappedKeys.join(', ') + '. I kept them exactly as recorded and I did not rename them.'] : [])
  .concat((unmappedKeys.length && missingRequired.length)
    ? ['One of those may be a required fact under the wrong name. Required and still missing: '
       + missingRequired.join(', ') + '. I will not assume which is which, so please confirm.'] : [])
  .concat((missingOptional.length && !requiresInfo)
    ? ['Optional details still outstanding, not blocking: ' + missingOptional.join(', ') + '.'] : []);
const noteText = notes.length ? ' ' + notes.join(' ') : '';

// D-TESTFLAG-01 (2026-08-25): Deterministic test-data stamp.
// The CONTROL set above reserves test_data_only as a system-injected field.
// No upstream node writes it; this stamps it unconditionally for every matter
// whose matter_id matches a canonical test prefix (MAT-TEST / MAT-QA / MAT-SANDBOX).
// String 'true' (not boolean) matches the truthy read in WF5 isTestMatter.
// Fail-closed: a blank or missing matter_id matches no prefix and receives no stamp,
// so a matter with an unrecognisable id is treated as production (conservative).
const _TEST_ID_RE = /^MAT-(?:TEST|QA|SANDBOX)/i;
if (_TEST_ID_RE.test(String(p.matter_id || '').trim())) {
  facts.test_data_only = 'true';
}

const common = {
  ...p,
  actions,
  plan_stamp: planStamp,
  facts_json: JSON.stringify(facts),
  missing_facts_json: JSON.stringify(missingRequired),
  optional_missing_facts_json: JSON.stringify(missingOptional),
  unknown_fact_keys_json: JSON.stringify(unknownKeys),
  unmapped_facts_json: JSON.stringify(unmappedFacts),
  unmapped_fact_keys_json: JSON.stringify(unmappedKeys),
  planner_contradictions_json: JSON.stringify(contradictions),
};

if (!force) {
  return [{ json: { ...common,
    risk_flags_json: JSON.stringify(Array.from(new Set(risks))),
    requires_information: requiresInfo,
    requires_human_review: needsReview,
    matter_status: requiresInfo ? 'NEEDS_INFORMATION' : 'CLASSIFIED',
    questions: requiresInfo ? deduped : [],
    owner_summary: String(p.owner_summary || '') + noteText,
    proceed_hint: requiresInfo
      ? 'If you cannot get a fact, send /proceed ' + p.matter_id
        + ' and I will record it as unobtainable and carry on. The gap stays on the record.'
      : '',
  }}];
}

// --- 3. forced proceed -----------------------------------------------------
const unobtainable = [];
for (const m of missingRequired) {
  if (hasRealValue(facts[m])) continue;
  facts[m] = 'UNOBTAINABLE_OWNER_CONFIRMED';
  unobtainable.push(m);
}

risks = risks.filter(r => String(r) !== 'MATERIAL_FACTS_MISSING');
if (unobtainable.length) risks.push('REQUIRED_FACTS_UNOBTAINABLE');
// /proceed records a missing required fact as an owner declaration of unobtainability.
// If the record also holds off-vocabulary facts, one of them may be the very fact just
// declared unobtainable. The declaration is the owner's to make, so it is not blocked,
// but it must not pass quietly.
if (unmappedKeys.length && unobtainable.length) risks.push('REQUIRED_FACT_MAY_BE_MISKEYED');
risks.push('REQUIRES_HUMAN_REVIEW');

return [{ json: { ...common,
  facts_json: JSON.stringify(facts),
  missing_facts_json: JSON.stringify([]),
  unobtainable_facts_json: JSON.stringify(unobtainable),
  risk_flags_json: JSON.stringify(Array.from(new Set(risks))),
  requires_information: false,
  requires_human_review: true,
  matter_status: 'CLASSIFIED',
  questions: [],
  forced_proceed: true,
  owner_summary: String(p.owner_summary || '')
    + (unobtainable.length
        ? ' You asked me to proceed without ' + unobtainable.length
          + ' required fact(s) that you cannot get: ' + unobtainable.join(', ')
          + '. I record them as your declaration. They are unobtainable facts, not verified findings. Every document shows the gap.'
        : ' You asked me to proceed. All required facts are present. I marked nothing as unobtainable.')
    + noteText,
}}];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf2",
  "nodeName": "Finalise Plan",
  "nodeId": "7a18e9d1-820c-4aa7-a84b-bab52f95bf74",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "d447a3340650f1a4fb986793d51347c6af598b10a624b1ec1988f082f9ff04e1"
} };
