// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf2
// Node name       : Playbook Library
// Node id         : 70cd180e-05e8-4c61-82fd-28226d4a2c5f
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 8f3c18fd9f6f499f5171ed56f5eb07c35cc7a828b4543a8e67cc4406780bd383
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./playbook-library');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
const PLAYBOOKS = {
 "employment_contract_v1": {
  "playbook_id": "employment_contract_v1",
  "name": "Employment contract (Australia / WA)",
  "jurisdiction": "WA/Australia",
  "intake_questions": [
   "Is the worker engaged as an employee or as an independent contractor?",
   "What is the full legal name of the employer, and its ABN or ACN?",
   "What is the full legal name of the worker?",
   "What is the role title and a short description of the duties?",
   "What is the primary workplace or work location?",
   "What is the intended start date?",
   "Is the employment full-time, part-time, casual, or fixed-term?",
   "What are the ordinary hours and the roster pattern?",
   "What is the pay rate, and is it hourly, weekly, or an annual salary?",
   "Is the stated figure gross or net?",
   "Which modern award or enterprise agreement applies, if any?",
   "Is the employer a constitutional corporation (Pty Ltd) or an unincorporated WA entity?",
   "Is there a probation period, and how long?",
   "What notice period applies on termination?",
   "Are confidentiality, intellectual property, or restraint terms required?",
   "Will the employer supply equipment, or reimburse expenses?"
  ],
  "required_facts": [
   "worker_classification",
   "employer_legal_name",
   "employer_abn",
   "worker_legal_name",
   "role_title",
   "duties_summary",
   "work_location",
   "start_date",
   "employment_type",
   "ordinary_hours",
   "pay_rate",
   "pay_basis",
   "gross_or_net",
   "award_or_agreement",
   "ir_system",
   "superannuation_treatment",
   "probation",
   "notice_period"
  ],
  "optional_facts": [
   "roster_pattern",
   "leave_entitlements_beyond_nes",
   "confidentiality_required",
   "ip_assignment_required",
   "restraint_required",
   "policies_incorporated",
   "privacy_and_monitoring",
   "equipment_provided",
   "expense_policy",
   "whs_notes"
  ],
  "required_evidence": [
   "Any existing offer letter or position description",
   "Any existing employment contract template the employer uses",
   "Any award classification the employer believes applies"
  ],
  "source_policy": [
   "https://www.wa.gov.au/organisation/private-sector-labour-relations/employment-contracts",
   "https://www.wa.gov.au/organisation/private-sector-labour-relations/which-system-of-employment-law-applies",
   "https://www.fairwork.gov.au/employment-conditions/national-employment-standards",
   "https://www.fairwork.gov.au/employment-conditions/awards"
  ],
  "issue_checklist": [
   "Confirm whether the national (Fair Work) system or the WA state system applies.",
   "Confirm whether a modern award covers the role and classification.",
   "Confirm the rate is not below the applicable minimum.",
   "Confirm superannuation treatment and whether the rate is inclusive or exclusive.",
   "Confirm NES entitlements are not contracted out of.",
   "Confirm the probation period does not purport to remove statutory entitlements.",
   "Confirm any restraint is reasonable in scope, area, and duration.",
   "Confirm IP and confidentiality terms match the actual role."
  ],
  "risk_flags": [
   "MISCLASSIFICATION_RISK",
   "BELOW_AWARD_RATE_RISK",
   "WRONG_IR_SYSTEM",
   "UNREASONABLE_RESTRAINT",
   "NES_CONTRACTING_OUT",
   "SUPER_TREATMENT_UNCLEAR"
  ],
  "draft_types": [
   "EMPLOYMENT_CONTRACT",
   "OFFER_LETTER",
   "ADVICE_NOTE"
  ],
  "action_templates": [
   {
    "action_type": "COLLECT_FACTS",
    "requires_approval": false
   },
   {
    "action_type": "RESEARCH_SOURCES",
    "requires_approval": false
   },
   {
    "action_type": "DRAFT_DOCUMENT",
    "requires_approval": false
   },
   {
    "action_type": "SEND_DOCUMENT",
    "requires_approval": true,
    "channel": "GMAIL"
   }
  ],
  "approval_rules": [
   "Any external send requires approval.",
   "Any signature step is manual and out of scope."
  ],
  "follow_up_rules": [
   {
    "after_days": 3,
    "when_status": "SENT",
    "action_type": "FOLLOW_UP"
   }
  ]
 },
 "contractor_agreement_v1": {
  "playbook_id": "contractor_agreement_v1",
  "name": "Independent contractor agreement (Australia / WA)",
  "jurisdiction": "WA/Australia",
  "intake_questions": [
   "What is the contractor's legal or trading name, and their ABN?",
   "Is the contractor registered for GST?",
   "What is the scope of services?",
   "What are the specific deliverables and milestones?",
   "What are the fees, and how are they calculated?",
   "What are the payment terms and invoicing arrangements?",
   "Who bears expenses?",
   "Who owns the work product and any intellectual property created?",
   "Are confidentiality terms required?",
   "What insurance must the contractor hold (public liability, professional indemnity, workers compensation)?",
   "May the contractor subcontract or delegate the work?",
   "Who controls how, when and where the person does the work?",
   "Does the contractor supply their own tools and equipment?",
   "Does the contractor work for other clients?",
   "What termination rights apply to each party?",
   "What dispute resolution process do you want?"
  ],
  "required_facts": [
   "contractor_legal_name",
   "contractor_abn",
   "gst_registered",
   "principal_legal_name",
   "scope_of_services",
   "deliverables",
   "fees",
   "payment_terms",
   "ip_ownership",
   "control_of_work",
   "tools_and_equipment",
   "delegation_right",
   "other_clients",
   "insurance_required",
   "term_and_termination"
  ],
  "optional_facts": [
   "milestones",
   "expenses",
   "confidentiality_required",
   "dispute_resolution",
   "site_access"
  ],
  "required_evidence": [
   "Any existing scope of works, quote, or statement of work",
   "Any prior agreement between the parties"
  ],
  "source_policy": [
   "https://www.wa.gov.au/organisation/private-sector-labour-relations/employee-or-independent-contractor",
   "https://www.fairwork.gov.au/find-help-for/independent-contractors",
   "https://www.fairwork.gov.au/find-help-for/independent-contractors/whole-of-relationship-test",
   "https://www.fairwork.gov.au/find-help-for/independent-contractors/sham-contracting"
  ],
  "issue_checklist": [
   "Apply the whole-of-relationship test. Do not rely on the label the parties use.",
   "Assess control, delegation, commercial risk, tools, goodwill, and integration into the business.",
   "Flag sham contracting risk where the practical relationship looks like employment.",
   "Confirm superannuation may still be payable to some contractors.",
   "Confirm insurance obligations and who carries them.",
   "Confirm IP assignment is express, because it does not always pass by default."
  ],
  "risk_flags": [
   "MISCLASSIFICATION_RISK",
   "SHAM_CONTRACTING_RISK",
   "SUPER_MAY_STILL_APPLY",
   "IP_NOT_ASSIGNED",
   "NO_INSURANCE_EVIDENCE",
   "UNCLEAR_SCOPE"
  ],
  "draft_types": [
   "CONTRACTOR_AGREEMENT",
   "SCOPE_OF_WORK",
   "ADVICE_NOTE"
  ],
  "action_templates": [
   {
    "action_type": "COLLECT_FACTS",
    "requires_approval": false
   },
   {
    "action_type": "RESEARCH_SOURCES",
    "requires_approval": false
   },
   {
    "action_type": "CLASSIFICATION_ASSESSMENT",
    "requires_approval": false
   },
   {
    "action_type": "DRAFT_DOCUMENT",
    "requires_approval": false
   },
   {
    "action_type": "SEND_DOCUMENT",
    "requires_approval": true,
    "channel": "GMAIL"
   }
  ],
  "approval_rules": [
   "Any external send requires approval."
  ],
  "follow_up_rules": [
   {
    "after_days": 3,
    "when_status": "SENT",
    "action_type": "FOLLOW_UP"
   }
  ]
 },
 "motor_vehicle_damage_v1": {
  "playbook_id": "motor_vehicle_damage_v1",
  "name": "Motor vehicle damage or collision (WA)",
  "jurisdiction": "WA/Australia",
  "intake_questions": [
   "What happened, in your own words?",
   "What is the date, time, and exact location of the incident?",
   "Were you present, and were you driving at the time?",
   "Do you know the other party's name, contact details, or insurer?",
   "Do you have the other vehicle's registration number?",
   "Do you have photographs or video of the damage and the scene?",
   "Is there CCTV, dashcam, or vehicle sentry footage?",
   "Do you have a repair quote or an assessment?",
   "Who is your insurer, and what is the policy number?",
   "Has a police report been made, and is there a report number?",
   "Are there any witnesses, and do you have their details?",
   "Has there been any contact with the other party so far?"
  ],
  "required_facts": [
   "incident_description",
   "incident_datetime",
   "incident_location",
   "owner_present",
   "driver_identity",
   "own_vehicle_registration",
   "damage_description"
  ],
  "optional_facts": [
   "other_party_name",
   "other_party_contact",
   "other_party_registration",
   "other_party_insurer",
   "police_report_number",
   "witness_details",
   "insurer_name",
   "policy_number",
   "repair_quote_amount",
   "prior_communications"
  ],
  "required_evidence": [
   "Photographs of the damage",
   "Photographs of the scene and the position of the vehicles",
   "Video or CCTV or dashcam footage if it exists",
   "Repair quote",
   "Any note left on the vehicle",
   "Any correspondence with the other party or an insurer"
  ],
  "source_policy": [
   "https://www.wa.gov.au/organisation/department-of-transport",
   "https://www.police.wa.gov.au/Crime/Report-a-crime",
   "https://www.icwa.wa.gov.au/",
   "https://www.magistratescourt.wa.gov.au/"
  ],
  "issue_checklist": [
   "Establish the facts before considering liability.",
   "Do not name a person as at fault. Record only what the evidence shows.",
   "Identify the limitation period, and mark it UNVERIFIED_ESTIMATE unless confirmed.",
   "Identify whether the claim is best made through insurance or directly.",
   "Identify whether a police report is required or useful.",
   "Preserve evidence. Include footage that a system can overwrite."
  ],
  "risk_flags": [
   "LIABILITY_UNDETERMINED",
   "OTHER_PARTY_UNIDENTIFIED",
   "EVIDENCE_MAY_EXPIRE",
   "LIMITATION_PERIOD_UNVERIFIED",
   "PRIVACY_RISK_IN_SHARING_FOOTAGE",
   "QUANTUM_UNVERIFIED"
  ],
  "draft_types": [
   "EVIDENCE_SUMMARY",
   "LETTER_TO_INSURER",
   "LETTER_OF_DEMAND",
   "POLICE_REPORT_SUMMARY",
   "ADVICE_NOTE"
  ],
  "action_templates": [
   {
    "action_type": "COLLECT_EVIDENCE",
    "requires_approval": false
   },
   {
    "action_type": "PRESERVE_FOOTAGE",
    "requires_approval": false
   },
   {
    "action_type": "OBTAIN_REPAIR_QUOTE",
    "requires_approval": false
   },
   {
    "action_type": "DRAFT_DOCUMENT",
    "requires_approval": false
   },
   {
    "action_type": "CONTACT_INSURER",
    "requires_approval": true,
    "channel": "GMAIL"
   },
   {
    "action_type": "SEND_DEMAND",
    "requires_approval": true,
    "channel": "GMAIL"
   }
  ],
  "approval_rules": [
   "Never contact police, an insurer, or the other party without approval.",
   "Never share footage or personal information externally without approval.",
   "Never state or accept liability."
  ],
  "follow_up_rules": [
   {
    "after_days": 7,
    "when_status": "SENT",
    "action_type": "FOLLOW_UP"
   }
  ]
 },
 "generic_legal_research_v1": {
  "playbook_id": "generic_legal_research_v1",
  "name": "Generic legal research and drafting",
  "jurisdiction": "WA/Australia",
  "intake_questions": [
   "What outcome do you want?",
   "Which parties are involved?",
   "What is the relevant jurisdiction?",
   "What are the key dates?",
   "What documents do you already hold?",
   "Is there a deadline you already know about?"
  ],
  "required_facts": [
   "objective",
   "parties",
   "jurisdiction",
   "key_dates",
   "documents_held"
  ],
  "optional_facts": [
   "known_deadline",
   "prior_advice",
   "budget_or_constraints"
  ],
  "required_evidence": [
   "Any document that defines the relationship or the dispute"
  ],
  "source_policy": [
   "https://www.legislation.gov.au/",
   "https://www.legislation.wa.gov.au/",
   "https://www.austlii.edu.au/",
   "https://www.wa.gov.au/"
  ],
  "issue_checklist": [
   "Identify the legal question precisely before researching.",
   "Prefer primary legislation and official regulator guidance.",
   "Mark every conclusion that is not supported by a retrieved source as UNVERIFIED.",
   "Recommend a lawyer where the matter is high value, urgent, or contested."
  ],
  "risk_flags": [
   "SCOPE_UNCLEAR",
   "NO_AUTHORITATIVE_SOURCE_FOUND",
   "HIGH_RISK_RECOMMEND_LAWYER"
  ],
  "draft_types": [
   "RESEARCH_NOTE",
   "LETTER",
   "ADVICE_NOTE"
  ],
  "action_templates": [
   {
    "action_type": "CLARIFY_SCOPE",
    "requires_approval": false
   },
   {
    "action_type": "RESEARCH_SOURCES",
    "requires_approval": false
   },
   {
    "action_type": "DRAFT_DOCUMENT",
    "requires_approval": false
   },
   {
    "action_type": "SEND_DOCUMENT",
    "requires_approval": true,
    "channel": "GMAIL"
   }
  ],
  "approval_rules": [
   "Any external send requires approval."
  ],
  "follow_up_rules": [
   {
    "after_days": 5,
    "when_status": "SENT",
    "action_type": "FOLLOW_UP"
   }
  ]
 }
};

const j = $input.first().json;
const catalogue = Object.values(PLAYBOOKS).map(p => ({
  playbook_id: p.playbook_id,
  name: p.name,
  jurisdiction: p.jurisdiction,
  covers: p.issue_checklist.slice(0, 3),
})); 
return [{ json: {
  ...j,
  playbooks: PLAYBOOKS,
  playbook_catalogue: JSON.stringify(catalogue, null, 1),
}}];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf2",
  "nodeName": "Playbook Library",
  "nodeId": "70cd180e-05e8-4c61-82fd-28226d4a2c5f",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "8f3c18fd9f6f499f5171ed56f5eb07c35cc7a828b4543a8e67cc4406780bd383"
} };
