// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf2
// Node name       : Resolve Matter
// Node id         : f2f9d98f-c11c-4c54-b40c-ec6f8261efab
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : f487ac13f5ae5306ba80ff9effc74649c94a91929cb872838c0fab1755401ec3
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./resolve-matter');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
const j = $('Playbook Library').first().json;
const rows = $input.all().map(i => i.json).filter(r => r && r.matter_id);

const wantId = String(j.matter_ref || j.session_matter_id || '').toUpperCase();
let existing = null;
if (wantId) {
  const hits = rows.filter(r => String(r.matter_id).toUpperCase() === wantId);
  if (hits.length) existing = hits[hits.length - 1];
}

const isContinuation = !!existing && ['CONTINUE_MATTER','CLARIFICATION_ANSWER','FOLLOW_UP_REQUEST','EVIDENCE_NOTE'].includes(j.route);

// Deterministic id. Sequence is derived from rows already on the register for today.
function newMatterId() {
  const d = new Date();
  const stamp = d.getUTCFullYear().toString()
    + String(d.getUTCMonth() + 1).padStart(2, '0')
    + String(d.getUTCDate()).padStart(2, '0');
  const prefix = 'MAT-' + stamp + '-';
  const used = rows
    .map(r => String(r.matter_id || ''))
    .filter(v => v.startsWith(prefix))
    .map(v => parseInt(v.slice(prefix.length), 10))
    .filter(n => !Number.isNaN(n));
  const next = (used.length ? Math.max(...used) : 0) + 1;
  return prefix + String(next).padStart(3, '0');
}

let known_facts = {};
let missing_facts = [];
// D8: Facts are loaded only when this is a genuine continuation of an existing matter.
// For NEW_MATTER routes isContinuation=false, so known_facts and missing_facts are
// always initialised empty — regardless of whether session_matter_id points at an
// existing matter on the register.
if (isContinuation && existing) {
  try { known_facts = JSON.parse(existing.facts_json || '{}'); } catch (e) { known_facts = {}; }
  try { missing_facts = JSON.parse(existing.missing_facts_json || '[]'); } catch (e) { missing_facts = []; }
}

return [{ json: {
  ...j,
  matter_id: isContinuation ? existing.matter_id : newMatterId(),
  is_new_matter: !isContinuation,
  // D9: metadata fields are gated on isContinuation, not just existing.
  // For NEW_MATTER routes these are always empty strings, even when a prior
  // active session points at an existing matter. This prevents previous-matter
  // metadata from reaching the Classify and Plan prompt.
  existing_status:       (existing && isContinuation) ? String(existing.status       || '') : '',
  existing_title:        (existing && isContinuation) ? String(existing.title        || '') : '',
  existing_playbook_id:  (existing && isContinuation) ? String(existing.playbook_id  || '') : '',
  existing_jurisdiction: (existing && isContinuation) ? String(existing.jurisdiction || '') : '',
  // Carried so Upsert Matter can preserve the original creation timestamp on a
  // continuation instead of overwriting it with now.
  //
  // Now gated on isContinuation as well, like its four siblings above. It used to
  // be gated on `existing` alone, on the reasoning that a row we are writing to
  // must keep its created_at even when the route is not a continuation. That case
  // cannot arise. Upsert Matter reads this field as:
  //     is_new_matter ? $now.toISO() : (existing_created_at || $now.toISO())
  // and is_new_matter is !isContinuation, so on every non-continuation route the
  // field is never consumed — Upsert Matter takes $now instead. A non-continuation
  // also always carries a freshly minted newMatterId(), and Upsert Matter matches
  // on matter_id, so it cannot be writing to a pre-existing row in the first place.
  //
  // Leaving it ungated meant a NEW_MATTER raised while a stale session pointed at
  // an older matter carried that older matter's creation timestamp in the in-flight
  // item. It never reached the sheet, but it was the previous matter's data inside
  // the new matter's execution context, and it was the one existing_* field that
  // could still do that. Observed on 2026-08-24, execution 395.
  existing_created_at:   (existing && isContinuation) ? String(existing.created_at || '') : '',
  known_facts_json: JSON.stringify(known_facts),
  open_questions_json: JSON.stringify(missing_facts),
}}];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf2",
  "nodeName": "Resolve Matter",
  "nodeId": "f2f9d98f-c11c-4c54-b40c-ec6f8261efab",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "f487ac13f5ae5306ba80ff9effc74649c94a91929cb872838c0fab1755401ec3"
} };
