// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf4
// Node name       : Approval Gate
// Node id         : 9564a873-d0f1-44a8-ba85-e139dc83a594
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : c7f80a9501332f5c4992e98638bcafc84f62abd16da8d881deeca17390322f4a
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./approval-gate');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// The approval gate. Claude has no part in this decision.
const cfg = $('Config').first().json;
const approvals = $('Load Approvals').all().map(i => i.json).filter(r => r && r.approval_id);
const actions   = $('Load Actions').all().map(i => i.json).filter(r => r && r.action_id);
const drafts    = $('Load Drafts').all().map(i => i.json).filter(r => r && r.draft_id);
const comms     = $('Load Communications').all().map(i => i.json).filter(r => r && r.communication_id);
const matters   = $('Load Matters').all().map(i => i.json).filter(r => r && r.matter_id);

const aprId = String(cfg.approval_id || '').toUpperCase();
const decision = String(cfg.decision || '').toUpperCase();
const chatId = String(cfg.chat_id || '');
const ownerId = String(cfg.owner_chat_id || '');
const dryRun = String(cfg.dry_run).toLowerCase() === 'true';

function out(o) { return [{ json: { ...cfg, dry_run: dryRun, ...o } }]; }

// 1. Only the owner may decide.
if (!ownerId || chatId !== ownerId)
  return out({ gate: 'INVALID', gate_reason: 'The decision did not come from the owner chat.' });

// 2. The approval must exist.
const hits = approvals.filter(a => String(a.approval_id).toUpperCase() === aprId);
if (!hits.length)
  return out({ gate: 'INVALID', gate_reason: 'Approval ' + aprId + ' is not on the register.' });
const apr = hits[hits.length - 1];

// 3. It must still be pending. A second decision is a duplicate, not a new one.
if (String(apr.status || '').toUpperCase() !== 'PENDING')
  return out({ gate: 'DUPLICATE', gate_reason:
    'Approval ' + aprId + ' was already decided as ' + (apr.decision || apr.status)
    + ' at ' + (apr.decided_at || 'an earlier time') + '.',
    approval_id: apr.approval_id, action_id: apr.action_id, matter_id: apr.matter_id });

// 4. The draft must exist and must not have changed since the approval was raised.
const dhits = drafts.filter(d => String(d.draft_id) === String(apr.draft_id));
if (!dhits.length)
  return out({ gate: 'INVALID', gate_reason: 'Draft ' + apr.draft_id + ' is missing.' });
const draft = dhits[dhits.length - 1];
if (String(draft.content_hash || '') !== String(apr.token_hash_or_reference || ''))
  return out({ gate: 'STALE', gate_reason:
    'The draft changed after I raised this approval. The approval is void. You must raise a new approval.',
    approval_id: apr.approval_id, action_id: apr.action_id, matter_id: apr.matter_id });

// 5. It must be the latest version for that action.
const chain = drafts.filter(d => String(d.action_id) === String(draft.action_id))
  .sort((a, b) => Number(a.version || 0) - Number(b.version || 0));
const latest = chain[chain.length - 1];
if (String(latest.draft_id) !== String(draft.draft_id))
  return out({ gate: 'STALE', gate_reason:
    'A newer draft (' + latest.draft_id + ') exists. Approve that one instead.',
    approval_id: apr.approval_id, action_id: apr.action_id, matter_id: apr.matter_id });

const ahits = actions.filter(a => String(a.action_id) === String(apr.action_id));
if (!ahits.length) return out({ gate: 'INVALID', gate_reason: 'Action ' + apr.action_id + ' is missing.' });
const action = ahits[ahits.length - 1];
const mhits = matters.filter(m => String(m.matter_id) === String(apr.matter_id));
const matter = mhits.length ? mhits[mhits.length - 1] : {};

// 5.5 The owner check at step 1 is tautological on its own: ownerId is a Config constant and
// chatId already passed WF1's own owner gate, so it can never fail. The matter's own
// owner_chat_id is an independent fact recorded when the matter was opened, so check it too.
const matterOwner = String(matter.owner_chat_id || '').trim();
if (matterOwner && matterOwner !== chatId)
  return out({ gate: 'INVALID', gate_reason:
    'A different chat owns this matter. I will not act on it.' });

// 5.6 delivery_mode is a stored instruction about how a legal document leaves the
// system, and it was normalised but never validated. The old line was
//   String(apr.delivery_mode || 'EMAIL_BODY').toUpperCase()
// which accepted any string and silently substituted EMAIL_BODY for a blank or
// missing value. An out-of-set value then fell through Delivery Route's fallback
// to the Drive/document path while Build Dry Run Report, whose map has no such
// key, described an email body instead - so the preview the owner approves from
// and the path that would actually run disagreed.
//
// WF4 can only ever write two values into that column: Build Draft Context picks
// PDF_ATTACHMENT or EMAIL_BODY, Validate Draft JSON carries that through, and
// Create Approval Request writes it. Mark Approval Approved / Rejected /
// Edit Requested never map the column. So anything outside the set on an
// Approvals row is a hand edit or a corrupted row, and is refused, not guessed at.
//
// The value must be TEXT. String() coercion is not enough on its own: String() of
// the single-element list ['EMAIL_BODY'] is the string 'EMAIL_BODY', so a non-text
// value could have satisfied a coercion-only check. A cell that is not text is
// malformed whatever it contains.
//
// Validated on the STORED value and BEFORE the APPROVE_LINK override below.
// DRIVE_LINK is a decision-time mode that is never persisted, so it must stay
// reachable; validating after the override would break APPROVE_LINK entirely.
//
// Case folding is unchanged for text, so a lower-case stored value still
// normalises and still passes. The silent default is gone: missing, blank,
// whitespace-only, non-text and unknown values all refuse. The refusal uses the
// existing INVALID contract, so it reaches Gate Result's fallback output, then
// Log Gate Refusal and Telegram - Gate Refused, with its reason preserved through
// Verify Selected Row.
const DELIVERY_MODES = ['EMAIL_BODY', 'PDF_ATTACHMENT'];
const rawDelivery = apr.delivery_mode;
const deliveryIsText = typeof rawDelivery === 'string';
const storedDelivery = deliveryIsText ? rawDelivery.toUpperCase() : '';
if (DELIVERY_MODES.indexOf(storedDelivery) === -1) {
  const shown = !deliveryIsText
    ? (rawDelivery === undefined ? '(missing)'
      : rawDelivery === null ? '(empty)'
      : 'a ' + (Array.isArray(rawDelivery) ? 'list' : typeof rawDelivery) + ' rather than text')
    : (rawDelivery.trim() === '' ? '(blank)' : '"' + rawDelivery + '"');
  return out({ gate: 'INVALID', gate_reason:
    'The approval records a delivery mode of ' + shown + '. That is not a delivery mode I '
    + 'implement. The only stored modes are EMAIL_BODY and PDF_ATTACHMENT. I will not guess '
    + 'how this document should leave the system, so nothing was sent and no state changed.' });
}

let delivery = storedDelivery;
if (decision === 'APPROVE_LINK') delivery = 'DRIVE_LINK';
const exportMime = delivery === 'DOCX_ATTACHMENT'
  ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  : 'application/pdf';
const exportExt = delivery === 'DOCX_ATTACHMENT' ? 'docx' : 'pdf';

let sourceRefs = [];
try { sourceRefs = JSON.parse(draft.source_refs_json || '[]'); } catch (e) { sourceRefs = []; }

// ---------------------------------------------------------------------------
// The logical delivery key.
//
// One approved delivery has one identity, and every retry of that delivery must
// resolve to the same identity. The key is derived only from data that exists
// BEFORE anything is sent: the approval, the action, the draft, the channel and
// the normalised recipient. A clock is excluded deliberately. The previous code
// stamped communication_id with $now, so a retry of the same approved delivery
// produced a second id and a second Communications row, and the sheet could no
// longer answer the only question that matters: was this actually sent?
//
// What changes the key, and therefore what may legitimately send again:
//   a new approval        -> new approval_id -> new key
//   an edited draft       -> new draft_id    -> new key
//   a different recipient -> new to=         -> new key
//   a different channel   -> new chan=       -> new key
// What does not change it: retrying, re-running the workflow, the time of day.
//
// delivery_mode is deliberately NOT part of the key. It is read from the approval
// row, so changing it requires a new approval, which already changes approval_id.
//
// The recipient is normalised before hashing, so "A. Smith <A.Smith@Example.COM>"
// and "a.smith@example.com" are one recipient and not two deliveries.
// ---------------------------------------------------------------------------
function normEmail(s) {
  const raw = String(s == null ? '' : s);
  const m = raw.match(/<([^>]+)>/);
  return String(m ? m[1] : raw).trim().toLowerCase();
}
// F-02. This was a single 32-bit FNV-1a pass returning 8 hex characters. 32 bits gives a
// birthday collision at roughly 1% by 10,000 deliveries, and a collision here is not a
// cosmetic clash: two different approved deliveries would share communication_id and
// send_key, so one would silently overwrite the other's Communications row and the sheet
// could no longer answer whether a particular legal communication was sent. The n8n Code
// sandbox has no crypto module, so this widens to 64 bits by running two independent
// FNV-1a passes with different offset bases over differently salted input. 64 bits puts
// the same 1% collision probability beyond 600 million deliveries.
//
// Widening changes the key format, so Communications rows written under the old 8-character
// key will not be matched by the new 16-character key. The first write per approval after
// this change appends rather than updates. That is a one-time effect and is expected.
function fnv1aPass(s, basis) {
  let h = basis >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h + (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24)) >>> 0;
  }
  return ('0000000' + h.toString(16)).slice(-8);
}
function fnv1aHex(str) {
  const s = String(str == null ? '' : str);
  return fnv1aPass(s, 0x811c9dc5) + fnv1aPass('K2|' + s + '|K2', 0x01000193);
}
const deliveryIdentity = 'apr=' + String(apr.approval_id || '').trim()
  + ' act=' + String(action.action_id || '').trim()
  + ' draft=' + String(draft.draft_id || '').trim()
  + ' chan=' + String(action.channel || 'NONE').trim().toUpperCase()
  + ' to=' + normEmail(action.recipient);
const deliveryHash = fnv1aHex(deliveryIdentity);

const common = {
  approval_id: apr.approval_id, action_id: action.action_id, matter_id: apr.matter_id,
  matter_title: String(matter.title || ''),
  draft_id: draft.draft_id, draft_version: Number(draft.version || 0),
  content: String(draft.content || ''),
  cover_note: String(draft.cover_note || ''),
  draft_type: String(draft.draft_type || 'DOCUMENT'),
  content_hash: String(draft.content_hash || ''),
  review_status: String(draft.review_status || ''),
  source_ref_count: Array.isArray(sourceRefs) ? sourceRefs.length : 0,
  recipient: String(action.recipient || ''),
  channel: String(action.channel || 'NONE').toUpperCase(),
  // The action's own key, unchanged. It identifies the ACTION for the Actions tab
  // and must not be confused with the delivery key below.
  idempotency_key: String(action.idempotency_key || (action.action_id + '|' + draft.content_hash)),
  // The logical delivery key. send_key is what every Communications write matches on;
  // communication_id_send and communication_id_dry are the deterministic row ids.
  delivery_key_parts: deliveryIdentity,
  delivery_hash: deliveryHash,
  send_key: 'SND-' + deliveryHash,
  dry_key: 'SND-' + deliveryHash + '|DRY',
  communication_id_send: 'COM-' + deliveryHash,
  communication_id_dry: 'COM-DRY-' + deliveryHash,
  subject: (String(matter.title || 'Matter') + ' [' + apr.matter_id + '][' + action.action_id + ']').slice(0, 200),
  delivery_mode: delivery, export_mime: exportMime, export_ext: exportExt,
  document_name: (apr.matter_id + ' ' + String(draft.draft_type || 'document') + ' ' + draft.draft_id),
};

if (decision === 'REJECT') return out({ ...common, gate: 'REJECTED', gate_reason: '' });
if (decision === 'REQUEST_EDIT' || decision === 'REQUEST_MORE_INFORMATION')
  return out({ ...common, gate: 'EDIT', gate_reason: '' });
if (decision !== 'APPROVE' && decision !== 'APPROVE_LINK')
  return out({ ...common, gate: 'INVALID', gate_reason: 'Unrecognised decision: ' + decision });

// 6. Send preconditions.
if (common.channel !== 'GMAIL')
  return out({ ...common, gate: 'INVALID', gate_reason: 'Action channel is ' + common.channel + ', not GMAIL. No send path exists.' });
if (!common.recipient || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(common.recipient))
  return out({ ...common, gate: 'INVALID', gate_reason: 'The action has no valid recipient email address.' });
if (/\[MISSING:/.test(common.content))
  return out({ ...common, gate: 'INVALID', gate_reason: 'The draft still contains [MISSING:] placeholders. I will not send it.' });

function suspectData(text) {
  const t = String(text || '');
  const found = [];
  if (/(\d)\1{5,}/.test(t.replace(/[^0-9]/g, ''))) found.push('a number with six or more identical digits in a row');
  if (/@(example|test|invalid|localhost)\.(com|org|net|au)?/i.test(t)) found.push('a reserved example email domain');
  if (/\b(lorem ipsum|placeholder|dummy|do not send|sample only)\b/i.test(t)) found.push('placeholder wording');
  if (/\bTEST\b/.test(t)) found.push('the word TEST in capitals');
  if (/\b(1234567|9876543|0123456)\d*\b/.test(t)) found.push('a sequential digit run');
  if (/\bX{4,}\b/i.test(t)) found.push('an XXXX placeholder');
  if (/\b(TBD|TBC)\b/.test(t)) found.push('TBD or TBC');
  if (/\b(this is (only )?a test|for testing (only|purposes)|synthetic (data|matter)|qa only)\b/i.test(t)) found.push('an explicit test declaration');
  return found;
}

// 6.5 Test or placeholder data in the DRAFT must never reach an outside party.
const suspect = suspectData(common.content + '\n' + common.subject + '\n' + common.recipient);
if (suspect.length)
  return out({ ...common, gate: 'INVALID', gate_reason:
    'The draft looks like it contains test or placeholder data, so I will not send it to an outside party.'
    + ' What I matched: ' + suspect.join('; ') + '.'
    + ' Correct the recorded fact and redraft, or reword the draft.' });

// 6.6 Unsourced legal assertions. Source retrieval does not currently work, so a statute, case
// citation or limitation period in a draft is model memory rather than anything retrieved.
// A purely factual notice cites nothing and passes untouched.
function citesLaw(text) {
  const t = String(text || '');
  const found = [];
  if (/\b[Ss]ection\s+\d+[A-Za-z]*\b/.test(t)) found.push('a section reference');
  if (/\bs\.?\s?\d+[A-Za-z]*\s+of\s+the\b/.test(t)) found.push('a pinpoint section reference');
  if (/\b[A-Z][A-Za-z ]*Act\s+(19|20)\d{2}\b/.test(t)) found.push('a named Act with a year');
  if (/\[(19|20)\d{2}\]\s*[A-Z]{2,6}\s*\d+/.test(t)) found.push('a case citation');
  if (/\b[Rr]egulation\s+\d+/.test(t)) found.push('a regulation reference');
  if (/\blimitation period (is|of|expires|runs)\b/i.test(t)) found.push('an asserted limitation period');
  if (/\byou are (legally )?(required|entitled|obliged)\b/i.test(t)) found.push('an asserted legal obligation or entitlement');
  return found;
}
const legal = citesLaw(common.content);
if (legal.length && common.source_ref_count === 0)
  return out({ ...common, gate: 'INVALID', gate_reason:
    'This draft states law but cites no retrieved source, so I will not send it.'
    + ' What I matched: ' + legal.join('; ') + '.'
    + ' Source retrieval does not work now. I cannot verify the law in this draft.'
    + ' Remove the legal statements. Then send it as a factual notice. Or verify the law yourself first.' });

// 6.7 The MATTER itself may be test data even when the letter reads cleanly. There is no
// is_test column on Matters, so this inspects the title, the recorded facts and the risk flags.
// The register currently holds matters explicitly titled TEST ONLY, and the fact store carries a
// placeholder phone number. A matter created to exercise the system must never be able to write
// to a real insurer, a car park operator or the police.
const matterBlob = String(matter.title || '') + '\n' + String(matter.facts_json || '')
  + '\n' + String(matter.risk_flags_json || '');
const matterSuspect = suspectData(matterBlob);
if (matterSuspect.length)
  return out({ ...common, gate: 'INVALID', gate_reason:
    'Matter ' + common.matter_id + ' looks like a test or practice matter, so I will not send anything from it.'
    + ' What I matched in the matter record: ' + matterSuspect.join('; ') + '.'
    + '\n\nIf this is a real matter, correct the recorded facts that look like placeholders and redraft.'
    + ' If it is a test, that is what this check is for.' });

// 7. Idempotency, in three cases.
const mine = comms.filter(c => String(c.action_id) === String(action.action_id));

// 7a. A confirmed send for this action blocks any further send.
const sent = mine.filter(c => String(c.direction || '').toUpperCase() === 'OUTBOUND');
if (sent.length)
  return out({ ...common, gate: 'DUPLICATE', gate_reason:
    'This action was already sent at ' + (sent[sent.length - 1].received_at || 'an earlier time')
    + ' (message ' + (sent[sent.length - 1].provider_message_id || 'unknown') + '). Not sending again.' });

// 7b. An unconfirmed attempt on this exact content. A previous run reached the send step and
// never confirmed, so whether the email went out is unknown. Ambiguity about whether a legal
// communication was delivered must fail closed.
const pending = mine.filter(c =>
  String(c.direction || '').toUpperCase() === 'OUTBOUND_PENDING' &&
  String(c.idempotency_key || '') === common.send_key);
if (pending.length)
  return out({ ...common, gate: 'DUPLICATE', gate_reason:
    'I tried to send this exact draft at '
    + (pending[pending.length - 1].received_at || 'an earlier time')
    + ' Nothing confirmed the send. I do not know if it went out.'
    + '\n\nLook in the sent mail for ' + common.recipient + '.'
    + '\nIf it went out, stop here.'
    + '\nIf it did not go out, send REQUEST_EDIT ' + common.approval_id
    + '. A new draft changes the content. That clears this block.' });

// 7b-2. F-04. An attempt whose outcome could not be established. Mark Send Failed used to
// stamp every error on the send path as OUTBOUND_FAILED, including a network timeout that may
// have occurred AFTER Gmail accepted the message. Because 7c deliberately ignores
// OUTBOUND_FAILED so that a known failure does not block a retry, an UNCERTAIN outcome was
// being converted into permission to send the same legal communication a second time.
// Classify Send Outcome now writes OUTBOUND_UNCERTAIN whenever it cannot prove the message
// never left the account, and an uncertain row blocks exactly like a pending one.
const uncertain = mine.filter(c =>
  String(c.direction || '').toUpperCase() === 'OUTBOUND_UNCERTAIN' &&
  String(c.idempotency_key || '') === common.send_key);
if (uncertain.length)
  return out({ ...common, gate: 'DUPLICATE', gate_reason:
    'An earlier attempt to send this exact draft did not report a usable outcome, so I do not'
    + ' know whether it was delivered. Recorded at '
    + (uncertain[uncertain.length - 1].received_at || 'an earlier time') + '.'
    + '\n\nWhat the send reported: '
    + (uncertain[uncertain.length - 1].summary || 'nothing usable') + '.'
    + '\n\nLook in the sent mail for ' + common.recipient + '.'
    + '\nIf it went out, stop here.'
    + '\nIf it did not go out, send REQUEST_EDIT ' + common.approval_id
    + '. A new draft changes the content. That clears this block.' });

// 7c. OUTBOUND_FAILED rows are deliberately ignored: a known failure must not block a retry.
// That exemption is now narrow: it applies only to outcomes Classify Send Outcome could prove
// never reached Gmail. Anything it could not prove is OUTBOUND_UNCERTAIN and is caught by 7b-2.
// DRY_RUN rows use OUTBOUND_DRY_RUN and never block a later real send.

// 7d. F-02. Hash collision detection. Widening the delivery key to 64 bits makes a collision
// vanishingly unlikely, but "unlikely" is not a control. delivery_key_parts is the full
// pre-image of the key; the Communications tab has no column for it, and adding one is a
// spreadsheet change outside this workflow. So the collision is detected here instead, by
// checking that any existing row carrying THIS key also carries this key's own identity.
// If the key matches but the approval, draft, action or recipient does not, two different
// deliveries have landed on one key and neither row can be trusted. Fail closed.
const keyRows = comms.filter(c =>
  String(c.idempotency_key || '') === common.send_key ||
  String(c.idempotency_key || '') === common.dry_key);
const collided = keyRows.filter(c =>
  (c.approval_id && String(c.approval_id) !== String(common.approval_id)) ||
  (c.draft_id && String(c.draft_id) !== String(common.draft_id)) ||
  (c.action_id && String(c.action_id) !== String(common.action_id)) ||
  (c.recipient && normEmail(c.recipient) !== normEmail(common.recipient)));
if (collided.length)
  return out({ ...common, gate: 'INVALID', gate_reason:
    'The delivery key for this approval already belongs to a different delivery, so the'
    + ' Communications record for one of them would be overwritten. I will not send.'
    + '\n\nThis key: ' + common.send_key + ' for approval ' + common.approval_id
    + ', draft ' + common.draft_id + ', action ' + common.action_id + '.'
    + '\nThe row already holding it: approval ' + (collided[0].approval_id || 'unknown')
    + ', draft ' + (collided[0].draft_id || 'unknown')
    + ', action ' + (collided[0].action_id || 'unknown') + '.'
    + '\n\nThis needs a human. Report it: a 64-bit delivery-key collision should be'
    + ' effectively impossible, so the more likely cause is a corrupted or hand-edited'
    + ' Communications row.' });

// 8. DRY_RUN. Every check above has passed. Nothing is written and nothing leaves the account.
if (dryRun) return out({ ...common, gate: 'DRY_RUN', gate_reason: 'DRY_RUN is on in the Config node.' });

return out({ ...common, gate: 'SEND', gate_reason: '' });
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf4",
  "nodeName": "Approval Gate",
  "nodeId": "9564a873-d0f1-44a8-ba85-e139dc83a594",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "c7f80a9501332f5c4992e98638bcafc84f62abd16da8d881deeca17390322f4a"
} };
