// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf4
// Node name       : Distil Sources
// Node id         : d342b856-c980-4b7b-a336-244e473c2818
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 323e5d6bf91f0785916a9824e7ade50891e6149525dbbeb8837a8aad64416068
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./distil-sources');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// Turns fetched pages into source records. Five faults were fixed here.
//
// 1. source_type was HARDCODED to 'OFFICIAL' for every page. A landing page, a block page,
//    a blog: all stamped official. The type is now derived from the host.
//
// 2. verification_status was decided by text.length > 400 alone, so navigation chrome on a
//    bare homepage passed as RETRIEVED and got cited by id in the draft. That is fabricated
//    authority, and it was the most dangerous defect in the build.
//
// 3. A federal legislation page returned 1.23 MB of text with no section heading marker and
//    was still graded RETRIEVED. That is a table of contents, not an authority. A heading
//    marker check now separates a real section body from an index (execution 300).
//
// 4. Every Sources row was written with the WRONG URL against its own title and excerpt,
//    pairwise swapped (execution 329, MAT-20260101-006). The url was resolved as
//    `j.url || (ctx.urls || [])[i]`. Fetch Source runs with fullResponse: true and returns
//    only data, headers, statusCode and statusMessage, so there is never a j.url and the
//    fallback always won. ctx.urls is the legacy list built by Build Draft Context, ordered
//    differently from the Source Registry that actually drove the fetches. The result was a
//    citation whose link points at a different Act: fabricated authority again, wearing a
//    correct-looking title. The fallback is DELETED. The Source Registry entry is the single
//    source of truth for url, title and identity.
//
//    Two independent controls, because one is not enough for a citation:
//
//    a. PROVENANCE. n8n stamps each Fetch Source response with pairedItem, naming the exact
//       Source Registry item that produced it. That is used instead of array position, so a
//       reordered, retried or partially failed fetch cannot re-pair one Act's body with
//       another Act's URL. If pairedItem is absent the record fails closed as
//       SOURCE_PROVENANCE_UNKNOWN. It does not guess by index.
//
//    b. CONTENT. Every registry entry declares `want` phrases taken from the operative
//       provision. If the fetched body does not contain them, the body is not the Act the
//       registry asked for, whatever the URL says, and the record fails closed as
//       SOURCE_MISALIGNED. This is what makes "the excerpt belongs to this URL" a checked
//       fact rather than an assumption.
//
//    source_id follows the REGISTRY position, not the response position, so the identity of
//    a row is a property of the registry entry rather than of arrival order.
//
// 5. The stored excerpt was text.slice(0, 6000), which on a consolidated Act is the cover
//    page and the table of contents (execution 335). All four sources were graded RETRIEVED
//    and handed to the drafter as four contents listings, while research_status read COMPLETE
//    and source_ref_count satisfied the Approval Gate's unsourced-law check. A draft could
//    therefore assert s 13 of the Limitation Act having never been shown the text of s 13:
//    right provenance, right citation, wrong content.
//
//    The excerpt is now anchored, using the scored heading logic proven in QA - Source
//    Retrieval Probe execution 323 (score 14 on all five registry URLs). In the stripped text
//    a real section body reads "13 .General limitation period" with a space before the dot,
//    while the contents listing reads "13.General limitation period" without one. Scoring on
//    that separates the operative provision from the index without hardcoding either.
//
//    Two new fail-closed statuses follow, deliberately distinct so a rejection says which
//    thing went wrong:
//      PINPOINT_ONLY_IN_CONTENTS the phrase appears, but never as a heading, so we are
//                                looking at a contents list and there is nothing to cite
//      EXCERPT_MISSING_PHRASE    the anchored excerpt does not itself contain a wanted
//                                phrase. This is the assertion the old code could not make:
//                                the check is against the text that is STORED and sent to the
//                                drafter, not against the full document.
//    A phrase absent from the body altogether is already SOURCE_MISALIGNED, so there is no
//    third rule for it.
//
//    The stored pinpoint is the anchored provision, e.g. "s 13". Deriving it by harvesting
//    structural words from the window instead produced "section 88; Division 2; Division 3;
//    section 7" for a row whose source is s 13 — those are cross-references inside s 13 — and
//    an empty cell for the Road Traffic row, whose window writes "Section 54" with a capital
//    S that the cross-reference regex does not match (execution 340). Cross-references are
//    still reported, under their own name.
//
//    Only ONE wanted phrase has to be heading-anchored. Requiring all of them would reject
//    genuine sources: the Road Traffic Act's second phrase, "report incident to police",
//    scores 4 rather than 14 because it is operative text rather than a heading, and
//    execution 323 shows exactly that pattern on the live page.
//
// The Code sandbox has no global URL constructor: "URL is not defined" (execution 297).
// Host and path parsing is by regex throughout, and must stay that way.
const ctx = $('Collect Evidence Text').first().json;
const registryItems = $('Source Registry').all();
const items = $input.all();
const stamp = new Date().toISOString();

function strip(html) {
  return String(html || '')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<nav[\s\S]*?<\/nav>/gi, ' ').replace(/<footer[\s\S]*?<\/footer>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ').trim();
}
function hostOf(url) { const m = String(url).match(/^https?:\/\/([^\/?#]+)/i); return m ? m[1].toLowerCase() : ''; }
function pathOf(url) { const m = String(url).match(/^https?:\/\/[^\/?#]+([^?#]*)/i); return m ? (m[1] || '') : ''; }

// What kind of thing is this, by publisher. Never a blanket 'OFFICIAL'.
function classifySource(url) {
  const h = hostOf(url);
  if (/(^|\.)legislation\.wa\.gov\.au$/.test(h)) return 'WA_LEGISLATION';
  if (/(^|\.)legislation\.gov\.au$/.test(h))    return 'CTH_LEGISLATION';
  if (/(^|\.)austlii\.edu\.au$/.test(h))        return 'CASE_LAW_DATABASE';
  if (/(^|\.)magistratescourt\.wa\.gov\.au$|(^|\.)supremecourt\.wa\.gov\.au$|(^|\.)districtcourt\.wa\.gov\.au$/.test(h)) return 'COURT';
  if (/(^|\.)fairwork\.gov\.au$/.test(h))       return 'REGULATOR_GUIDANCE';
  if (/\.gov\.au$/.test(h))                      return 'GOVERNMENT_GUIDANCE';
  return 'UNOFFICIAL';
}

const BLOCKED = /(enable javascript|access denied|are you a robot|request blocked|captcha|403 forbidden|cloudflare)/i;
const LEGAL_STRUCTURE = /\b(section\s+\d+|s\.?\s?\d+[A-Za-z]?\b|Part\s+[IVX0-9]+|Division\s+\d+|Schedule\s+\d+|subsection)\b/;
// An app shell carries navigation, not law. The body arrives before the text does.
const SPA_SHELL = /ng-version=|<app-root|__NEXT_DATA__|<div id="root"><\/div>/i;
// A real section body reads "13 .General limitation period". An index entry does not.
const HEADING_MARKER = /(^|\s)\d{1,4}[A-Za-z]?\s?\.\s?[A-Z]/;
const LEGISLATION = ['WA_LEGISLATION','CTH_LEGISLATION','CASE_LAW_DATABASE'];

// A status that means something. Only RETRIEVED may be relied on.
function verify(url, rawBody, text, type) {
  if (!text || text.length <= 400) return 'RETRIEVAL_FAILED';
  if (BLOCKED.test(text.slice(0, 3000))) return 'BLOCKED_BY_SITE';
  if (SPA_SHELL.test(String(rawBody).slice(0, 20000))) return 'SPA_SHELL_NOT_TEXT';
  // A bare host is a front door, not an authority.
  if (pathOf(url).replace(/\/+$/, '') === '') return 'LANDING_PAGE_NOT_AUTHORITY';
  // Legislation or case law with no structural marker is an index or a search form.
  if (LEGISLATION.includes(type) && !LEGAL_STRUCTURE.test(text)) return 'NO_PINPOINT_FOUND';
  // A structural word alone is not enough: a contents list is full of them.
  if (LEGISLATION.includes(type) && !HEADING_MARKER.test(text)) return 'NO_PINPOINT_FOUND';
  return 'RETRIEVED';
}

function pinpointsIn(text) {
  const found = [];
  const re = /\b(?:section\s+\d+[A-Za-z]*|Part\s+[IVX0-9]+|Division\s+\d+|Schedule\s+\d+)\b/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (found.indexOf(m[0]) === -1) found.push(m[0]);
    if (found.length >= 12) break;
  }
  return found.join('; ');
}

// ---------------------------------------------------------------------------------------
// Heading-anchored excerpting. Ported verbatim in behaviour from QA - Source Retrieval Probe
// (hNw2SnG6NB5KO88z), which scored 14 on all five registry URLs in execution 323.
//
// Anchoring problem: every Act's HTML opens with a table of contents that repeats each
// section heading word for word, so first-match anchoring returns the contents listing and
// last-match anchoring returns whichever later section happens to reuse the phrase. In the
// stripped body a real heading is preceded by a section number rendered as digits, spaces
// and a dot ("55 .Driver in incident..."), while the contents listing has no space
// ("55.Driver in incident..."). Score on that and the body wins.
// ---------------------------------------------------------------------------------------
const HEADING_BEFORE = /\d+[A-Za-z]?\s+\.\s*$/;
// Same pattern, capturing the section number so the row can record WHICH provision it is.
const HEADING_CAPTURE = /(\d+[A-Za-z]?)\s+\.\s*$/;
const HEADING_SCORE = 10;
const EXCERPT_BEFORE = 150;
const EXCERPT_AFTER = 2600;
const EXCERPT_CAP = 9000;

function bestOccurrence(text, lower, phrase) {
  const needle = String(phrase).toLowerCase();
  let from = 0;
  let best = -1;
  let bestScore = -1;
  let bestSection = '';
  for (;;) {
    const i = lower.indexOf(needle, from);
    if (i < 0) break;
    const before = text.slice(Math.max(0, i - 12), i);
    let score = 0;
    const hm = before.match(HEADING_CAPTURE);
    if (hm) score += HEADING_SCORE;
    const after = text.slice(i + needle.length, i + needle.length + 400);
    if (/\(1\)|\(a\)|means\s|must\s|is not to be/.test(after)) score += 4;
    if (/\d{1,3}\s*$/.test(after)) score -= 3;
    if (score > bestScore) { bestScore = score; best = i; bestSection = hm ? hm[1] : ''; }
    from = i + 1;
  }
  return { index: best, score: bestScore, section: bestSection };
}

function anchoredExcerpt(text, want) {
  const list = Array.isArray(want) ? want : [];
  const lower = String(text || '').toLowerCase();
  const chunks = [];
  const scores = [];
  const anchoredPhrases = [];
  const missingPhrases = [];
  const anchorPinpoints = [];
  let anchorHeading = '';
  for (const w of list) {
    const r = bestOccurrence(text, lower, w);
    if (r.index < 0) { missingPhrases.push(String(w)); continue; }
    scores.push(r.score);
    if (r.score >= HEADING_SCORE) {
      anchoredPhrases.push(String(w));
      if (!anchorHeading) anchorHeading = text.slice(Math.max(0, r.index - 12), r.index + 90).trim();
      // The pinpoint of a source is the provision the excerpt is anchored to, not whatever
      // cross-references happen to sit inside it. Harvesting the window produced
      // "section 88; Division 2; Division 3; section 7" for a row whose source IS s 13, and
      // an empty cell for the Road Traffic row because its window says "Section 54" with a
      // capital S, which the cross-reference regex does not match (execution 340).
      if (r.section && anchorPinpoints.indexOf('s ' + r.section) === -1) {
        anchorPinpoints.push('s ' + r.section);
      }
    }
    chunks.push(text.slice(Math.max(0, r.index - EXCERPT_BEFORE), r.index + EXCERPT_AFTER));
  }
  return {
    excerpt: chunks.join(' ----- ').slice(0, EXCERPT_CAP),
    scores, anchoredPhrases, missingPhrases, anchorPinpoints,
    anchorHeading, declared: list.length, foundCount: chunks.length,
  };
}

// Which Source Registry entry produced this response. pairedItem only; no positional guess.
function registryIndexOf(it) {
  const pi = it ? it.pairedItem : null;
  if (typeof pi === 'number') return { idx: pi, how: 'PAIRED_ITEM' };
  if (pi && !Array.isArray(pi) && typeof pi === 'object' && typeof pi.item === 'number') {
    return { idx: pi.item, how: 'PAIRED_ITEM' };
  }
  if (Array.isArray(pi) && pi.length && pi[0] && typeof pi[0].item === 'number') {
    return { idx: pi[0].item, how: 'PAIRED_ITEM' };
  }
  return { idx: -1, how: 'NO_PROVENANCE' };
}

// Does the body actually contain the provision the registry asked for?
function wantCheck(text, want) {
  const lower = String(text || '').toLowerCase();
  const list = Array.isArray(want) ? want : [];
  const found = [];
  const missing = [];
  for (const w of list) {
    if (lower.indexOf(String(w).toLowerCase()) !== -1) found.push(String(w));
    else missing.push(String(w));
  }
  return { found, missing, declared: list.length };
}

const sources = [];
items.forEach((it, i) => {
  const j = it.json || {};
  const prov = registryIndexOf(it);
  const regItem = prov.idx >= 0 ? registryItems[prov.idx] : null;
  const reg = regItem ? (regItem.json || {}) : null;

  const body = typeof j.data === 'string' ? j.data : (typeof j.body === 'string' ? j.body : '');
  const text = strip(body);
  const titleMatch = String(body).match(/<title[^>]*>([\s\S]{0,200}?)<\/title>/i);
  const documentTitle = titleMatch ? strip(titleMatch[1]) : '';
  const fetchError = j.error ? String((j.error && j.error.message) || j.error).slice(0, 300) : '';
  const httpStatus = (j.statusCode === 0 || j.statusCode) ? Number(j.statusCode) : null;

  // Identity follows the registry entry, so a row's id is a property of the entry.
  const seq = (prov.idx >= 0 ? prov.idx : i) + 1;
  const source_id = 'SRC-' + String(ctx.matter_id || '').replace('MAT-', '') + '-' + String(seq).padStart(2, '0');

  if (!reg || !reg.url) {
    // No provable link back to a registry entry means no citable source. Fail closed.
    sources.push({
      source_id, matter_id: ctx.matter_id,
      title: 'UNKNOWN SOURCE, PROVENANCE NOT ESTABLISHED',
      url: '', publisher: '', retrieved_at: stamp,
      jurisdiction: ctx.jurisdiction, source_type: 'UNOFFICIAL',
      relevance: ctx.playbook_name, pinpoints: '',
      verification_status: 'SOURCE_PROVENANCE_UNKNOWN',
      requested_url: '', registry_index: prov.idx, provenance: prov.how,
      registry_cite: '', document_title: documentTitle,
      want_declared: 0, want_found: '', want_missing: '', alignment_ok: false,
      http_status: httpStatus, raw_bytes: String(body).length, text_chars: text.length,
      heading_marker: HEADING_MARKER.test(text), fetch_error: fetchError,
      rejection_reason: 'SOURCE_PROVENANCE_UNKNOWN', excerpt: '',
    });
    return;
  }

  const requestedUrl = String(reg.url);
  const type = classifySource(requestedUrl);
  const wc = wantCheck(text, reg.want);
  const ax = anchoredExcerpt(text, reg.want);
  let status = verify(requestedUrl, body, text, type);

  // A body that does not contain the wanted provision is not this Act, whatever the URL says.
  if (status === 'RETRIEVED' && wc.declared > 0 && wc.missing.length > 0) status = 'SOURCE_MISALIGNED';
  // No separate "phrase absent" rule here on purpose. If every declared phrase were missing
  // from the body, wc.missing would already be non-empty and the SOURCE_MISALIGNED line above
  // would have fired, so such a rule would be dead code. PINPOINT_NOT_FOUND is still returned
  // by verify() for a legislation page carrying no section structure at all.
  // Present, but never preceded by a section-number heading marker: a contents list.
  if (status === 'RETRIEVED' && ax.declared > 0 && ax.anchoredPhrases.length === 0) status = 'PINPOINT_ONLY_IN_CONTENTS';

  // THE STORED-EXCERPT ASSERTION. Everything above reasons about the full fetched body. This
  // is the only check that reasons about the text that will actually be written to the sheet
  // and handed to the drafter. It is what execution 335 had no way of failing.
  const excerptLower = String(ax.excerpt || '').toLowerCase();
  const missingFromExcerpt = (Array.isArray(reg.want) ? reg.want : [])
    .filter(w => excerptLower.indexOf(String(w).toLowerCase()) === -1)
    .map(String);
  if (status === 'RETRIEVED' && missingFromExcerpt.length > 0) status = 'EXCERPT_MISSING_PHRASE';

  const usable = status === 'RETRIEVED';

  sources.push({
    source_id,
    matter_id: ctx.matter_id,
    // The registry cite is the authority's name. The page's own <title> is a diagnostic:
    // legislation.wa.gov.au serves titles like "Limitation Act 2005 00-g0-00 Xml".
    title: String(reg.cite || documentTitle || requestedUrl),
    url: requestedUrl,
    publisher: hostOf(requestedUrl),
    retrieved_at: stamp,
    jurisdiction: ctx.jurisdiction,
    source_type: type,
    relevance: ctx.playbook_name,
    // The pinpoint IS the anchored provision. pinpointsIn() over the window is kept only as
    // a fallback for a source whose heading marker carried no section number, and its raw
    // output is reported separately as cross_references so the two are never confused.
    pinpoints: usable ? (ax.anchorPinpoints.length ? ax.anchorPinpoints.join('; ') : pinpointsIn(ax.excerpt)) : '',
    verification_status: status,
    // Diagnostics. These do not reach the Sources tab; they exist so an execution can be
    // audited source by source, and so the alignment claim can be checked rather than trusted.
    requested_url: requestedUrl,
    registry_index: prov.idx,
    provenance: prov.how,
    registry_cite: String(reg.cite || ''),
    document_title: documentTitle,
    want_declared: wc.declared,
    want_found: wc.found.join(' | '),
    want_missing: wc.missing.join(' | '),
    // alignment_ok now means: the body is this Act AND the stored excerpt proves it.
    alignment_ok: wc.declared > 0 && wc.missing.length === 0 && missingFromExcerpt.length === 0,
    anchor_heading: ax.anchorHeading,
    anchor_pinpoints: ax.anchorPinpoints.join('; '),
    cross_references: usable ? pinpointsIn(ax.excerpt) : '',
    anchor_scores: ax.scores.join(','),
    anchored_phrases: ax.anchoredPhrases.join(' | '),
    phrases_missing_from_excerpt: missingFromExcerpt.join(' | '),
    excerpt_is_anchored: ax.anchoredPhrases.length > 0,
    excerpt_chars: String(ax.excerpt || '').length,
    http_status: httpStatus,
    raw_bytes: String(body).length,
    text_chars: text.length,
    heading_marker: HEADING_MARKER.test(text),
    fetch_error: fetchError,
    rejection_reason: usable ? '' : status,
    // NEVER text.slice(0, 6000). On a consolidated Act that is the cover page and the
    // contents list, which is what execution 335 stored for all four sources.
    excerpt: usable ? ax.excerpt : '',
  });
});

const retrieved = sources.filter(s => s.verification_status === 'RETRIEVED');
const legalRetrieved = retrieved.filter(s => LEGISLATION.includes(s.source_type));
const requiredCandidates = sources.filter(s => LEGISLATION.includes(s.source_type));
const requiredFailed = requiredCandidates.filter(s => s.verification_status !== 'RETRIEVED');
const landing = sources.filter(s => s.verification_status === 'LANDING_PAGE_NOT_AUTHORITY');
const blocked = sources.filter(s => s.verification_status === 'BLOCKED_BY_SITE');
const nopin = sources.filter(s => s.verification_status === 'NO_PINPOINT_FOUND');
const shells = sources.filter(s => s.verification_status === 'SPA_SHELL_NOT_TEXT');
const misaligned = sources.filter(s => s.verification_status === 'SOURCE_MISALIGNED');
const unprovenanced = sources.filter(s => s.verification_status === 'SOURCE_PROVENANCE_UNKNOWN');
const contentsOnly = sources.filter(s => s.verification_status === 'PINPOINT_ONLY_IN_CONTENTS');
const excerptShort = sources.filter(s => s.verification_status === 'EXCERPT_MISSING_PHRASE');

return [{ json: { ...ctx,
  sources,
  sources_retrieved: retrieved.length,
  sources_failed: sources.length - retrieved.length,
  sources_landing_pages: landing.length,
  sources_blocked: blocked.length,
  sources_without_pinpoint: nopin.length,
  sources_app_shells: shells.length,
  sources_misaligned: misaligned.length,
  sources_provenance_unknown: unprovenanced.length,
  sources_contents_only: contentsOnly.length,
  sources_excerpt_missing_phrase: excerptShort.length,
  excerpts_all_anchored: sources.length > 0 && sources.every(s => s.excerpt_is_anchored === true),
  pinpoints_all_present: sources.length > 0 && sources.every(s => s.verification_status !== 'RETRIEVED' || !!s.pinpoints),
  sources_legal_retrieved: legalRetrieved.length,
  sources_required_total: requiredCandidates.length,
  sources_required_failed: requiredFailed.length,
  alignment_all_ok: sources.length > 0 && sources.every(s => s.alignment_ok),
  // UNVERIFIED unless something genuinely citable came back. Validate Draft JSON turns
  // UNVERIFIED into NEEDS_HUMAN_REVIEW, and the Approval Gate refuses to send a draft that
  // states law while citing no source.
  research_status: legalRetrieved.length === 0
    ? 'UNVERIFIED'
    : ((retrieved.length === sources.length && requiredFailed.length === 0) ? 'COMPLETE' : 'PARTIAL'),
}}];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf4",
  "nodeName": "Distil Sources",
  "nodeId": "d342b856-c980-4b7b-a336-244e473c2818",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "323e5d6bf91f0785916a9824e7ade50891e6149525dbbeb8837a8aad64416068"
} };
