// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf4
// Node name       : Expand Sources
// Node id         : e06134c2-327f-44f2-9927-18b14ada008a
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 69abc968d346ac51262ae7da45a8034c7e86acb611644b63098a425a52a2c720
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./expand-sources');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
return ($input.first().json.sources || []).map(s => ({ json: s }));
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf4",
  "nodeName": "Expand Sources",
  "nodeId": "e06134c2-327f-44f2-9927-18b14ada008a",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "69abc968d346ac51262ae7da45a8034c7e86acb611644b63098a425a52a2c720"
} };
