// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf4
// Node name       : Integrity Guard
// Node id         : 7bee0e49-ab5e-471d-9a88-4da7d736e459
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 039f3be3be2522fd5f38a3941912231cab0f9a348b0ba6a020bac34a374bbe22
//
// The code between the BEGIN/END markers below is byte-identical to the
// node's parameters.jsCode in the workflow export. Everything outside the
// markers is harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./integrity-guard');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// ============================================================================
// INTEGRITY GUARD — fail closed before drafting, approval, state writes or send.
//
// WHY THIS EXISTS. action_id is not unique in the Actions register. 7 ids hold 2
// rows each, and idempotency_key is duplicated on 6 of them, so neither column
// identifies a row. Two independent selection faults follow from that:
//
//   READ vs READ.  Reselect Action If Drafted takes ready[0] (FIRST match) and is
//   authoritative for what gets drafted. Approval Gate takes ahits[length-1]
//   (LAST match) and validates recipient and channel. On ACT-20260101-001-005
//   those are different rows: OBTAIN_REPAIR_QUOTE / "preferred repairer" / MANUAL
//   versus FOLLOW_UP / "Riverside car park/centre management" / GMAIL.
//
//   READ vs WRITE.  Google Sheets appendOrUpdate updates the FIRST match, while
//   almost every reader in this workflow takes the LAST. So a send can be recorded
//   against one row while a different row stays open.
//
// HOW THE GUARD CLOSES BOTH. It does not choose between rows and it does not rank
// them. It refuses to let the branch continue whenever more than one row could be
// selected. When it passes, every in-scope action_id resolves to exactly ONE row,
// so first === last === newest === oldest, and both mismatches become unreachable
// rather than merely unlikely. Containment by elimination, not by arbitration.
//
// It never uses updated_at, created_at, row order or row number to prefer a row.
// Those appear only in the conflict report, so a human can tell the rows apart.
//
// Nothing here writes, approves, drafts, sends or mutates. Read-only.
// ============================================================================

const cfg = $('Config').first().json;
const passthrough = $input.first().json;
const actions = $('Load Actions').all().map(i => i.json).filter(r => r && r.action_id);
const approvals = (() => { try { return $('Load Approvals').all().map(i => i.json).filter(r => r && r.approval_id); }
                           catch (e) { return []; } })();

const S = v => String(v === null || v === undefined ? '' : v).trim();
const U = v => S(v).toUpperCase();

// Content fingerprint. Excludes mutable state (status, updated_at, draft_id,
// approval_id, blocked_reason) so a row stays identifiable across a legal update.
const FP_FIELDS = ['action_id', 'matter_id', 'action_type', 'priority', 'depends_on_json',
  'recipient', 'channel', 'requires_approval', 'idempotency_key', 'created_at'];
function fnv(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return ('00000000' + h.toString(16)).slice(-8);
}
function fingerprint(row) {
  const basis = FP_FIELDS.map(f => S(row[f])).join('|');
  return 'FP-' + fnv(basis) + fnv(basis.split('').reverse().join('') + '|salt2');
}
function rowRef(row, idx) {
  return { snapshot_index: idx, fingerprint: fingerprint(row),
    action_id: S(row.action_id), idempotency_key: S(row.idempotency_key),
    action_type: U(row.action_type), created_at: S(row.created_at) };
}

function halt(code, reason, detail) {
  return [{ json: {
    ...passthrough,
    integrity_ok: false,
    gate: 'DATA_INTEGRITY_CONFLICT',
    integrity_code: code,
    integrity_reason: reason,
    integrity_detail: detail || [],
    // Deliberately absent: any selected row, any winner, any ranking.
  } }];
}

// ---- 1. Establish scope -----------------------------------------------------
// APPROVAL route: the one action the approval names.
// DRAFT route: every action on the matter, because Reselect chooses among them,
// so ambiguity anywhere in that set can change which action is drafted.
const routeGroup = U(cfg.route_group);
let scopeIds = [];
let scopeLabel = '';

if (routeGroup === 'APPROVAL') {
  const aprId = S(cfg.approval_id);
  const hits = approvals.filter(a => S(a.approval_id) === aprId);
  if (!aprId) return halt('NO_APPROVAL_ID', 'The approval route ran without an approval_id.');
  if (!hits.length) return halt('APPROVAL_NOT_FOUND', 'Approval ' + aprId + ' is not on the register.');
  if (hits.length > 1) {
    return halt('DUPLICATE_APPROVAL_ROW',
      'Approval ' + aprId + ' appears on ' + hits.length + ' rows. I will not choose between them.',
      hits.map(h => ({ approval_id: h.approval_id, action_id: h.action_id, draft_id: h.draft_id })));
  }
  scopeIds = [S(hits[0].action_id)];
  scopeLabel = 'approval ' + aprId;
} else {
  const matterId = S(cfg.matter_id);
  if (!matterId) return halt('NO_MATTER_ID', 'No matter_id in scope.');
  const mine = actions.filter(a => S(a.matter_id) === matterId);
  if (!mine.length) return halt('NO_ACTIONS_FOR_MATTER', 'Matter ' + matterId + ' has no action rows.');
  scopeIds = Array.from(new Set(mine.map(a => S(a.action_id))));
  scopeLabel = 'matter ' + matterId;
}

// ---- 2-5. Ambiguity checks. Any one of them stops the branch. ---------------
const conflicts = [];
const selected = {};

// Blank identifiers are themselves ambiguity: they cannot address a row.
actions.filter(a => S(a.matter_id) === S(cfg.matter_id) || scopeIds.indexOf(S(a.action_id)) !== -1)
  .forEach((a, i) => {
    if (!S(a.action_id)) conflicts.push({ code: 'BLANK_ACTION_ID', snapshot_index: i });
    if (!S(a.idempotency_key)) conflicts.push({ code: 'BLANK_IDEMPOTENCY_KEY', action_id: S(a.action_id) });
  });

// 3. Duplicate idempotency_key anywhere in scope, even across different action ids.
const keyIndex = {};
actions.forEach((a, i) => {
  if (scopeIds.indexOf(S(a.action_id)) === -1) return;
  const k = S(a.idempotency_key);
  if (!k) return;
  (keyIndex[k] = keyIndex[k] || []).push(rowRef(a, i));
});
Object.keys(keyIndex).forEach(k => {
  if (keyIndex[k].length > 1) {
    conflicts.push({ code: 'DUPLICATE_IDEMPOTENCY_KEY', idempotency_key: k, rows: keyIndex[k] });
  }
});

// 2 + 4 + 5. Duplicate action_id, and field mismatch between rows sharing one id.
const COMPARE = ['action_type', 'recipient', 'channel', 'requires_approval',
  'depends_on_json', 'idempotency_key', 'matter_id'];

scopeIds.forEach(id => {
  const rows = [];
  actions.forEach((a, i) => { if (S(a.action_id) === id) rows.push({ row: a, ref: rowRef(a, i) }); });

  if (rows.length === 0) {
    conflicts.push({ code: 'ACTION_NOT_FOUND', action_id: id });
    return;
  }
  if (rows.length > 1) {
    const differing = COMPARE.filter(f =>
      Array.from(new Set(rows.map(r => f === 'requires_approval' || f === 'action_type' || f === 'channel'
        ? U(r.row[f]) : S(r.row[f])))).length > 1);
    conflicts.push({
      code: differing.length ? 'DUPLICATE_ACTION_ID_FIELD_MISMATCH' : 'DUPLICATE_ACTION_ID',
      action_id: id,
      row_count: rows.length,
      differing_fields: differing,
      // Candidates listed so a human can tell them apart. Order is register order.
      // It carries no meaning and confers no preference.
      candidates: rows.map(r => r.ref),
    });
    return;
  }
  selected[id] = rows[0].ref;   // exactly one row: first === last, unambiguous
});

if (conflicts.length) {
  const worst = conflicts[0];
  return halt(worst.code,
    'More than one Action row could be selected for ' + scopeLabel
    + '. I will not choose between them, and I will not draft, approve, write state or send'
    + ' until a human decides which row is the action. ' + conflicts.length + ' conflict(s) found.',
    conflicts);
}

// ---- Unambiguous. Carry the selection forward. ------------------------------
const scopeFingerprint = 'SCOPE-' + fnv(scopeIds.slice().sort()
  .map(id => id + ':' + selected[id].fingerprint).join('|'));

return [{ json: {
  ...passthrough,
  integrity_ok: true,
  integrity_code: 'OK',
  integrity_scope: scopeLabel,
  integrity_scope_ids: scopeIds,
  integrity_scope_fingerprint: scopeFingerprint,
  selected_rows: selected,
  // Convenience for the approval route, where scope is a single action.
  selected_action_id: scopeIds.length === 1 ? scopeIds[0] : '',
  selected_row_fingerprint: scopeIds.length === 1 ? selected[scopeIds[0]].fingerprint : '',
  selected_row_reference: scopeIds.length === 1 ? selected[scopeIds[0]].snapshot_index : -1,
} }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf4",
  "nodeName": "Integrity Guard",
  "nodeId": "7bee0e49-ab5e-471d-9a88-4da7d736e459",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "039f3be3be2522fd5f38a3941912231cab0f9a348b0ba6a020bac34a374bbe22"
} };
