// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.
// Source workflow : wf4
// Node name       : Integrity Guard
// Node id         : 7bee0e49-ab5e-471d-9a88-4da7d736e459
// Node mode       : runOnceForAllItems
// sha256(jsCode)  : 039f3be3be2522fd5f38a3941912231cab0f9a348b0ba6a020bac34a374bbe22
//                   ^ the sha of the PUBLISHED node, as captured in
//                     exports/wf4.active.json and harness/units/index.json.
//                     Left untouched on purpose: it is the record of what is
//                     running in n8n right now.
//
// 2026-08-28 -- THIS FILE NOW DIVERGES FROM THAT SHA, DELIBERATELY.
// The block between the BEGIN/END markers carries the FINDINGS.md section 1 fix
// (conflict severity ranking + distinct in-scope action_id count). It has NOT
// been ported to the n8n draft and has NOT been published, so the live node
// still headlines DUPLICATE_IDEMPOTENCY_KEY. Re-running
// .tooling/extract-units.py against the current exports/wf4.active.json WILL
// overwrite this fix -- port it to the draft and have the owner publish first,
// then re-extract. Everything outside the markers is still harness scaffolding.
//
// Usage:
//   const { makeContext } = require('../../n8n-shim');
//   const unit = require('./integrity-guard');
//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},
//                                            now: '2026-01-01T00:00:00.000Z' }));
'use strict';

// The parameter is deliberately named __n8nCtx: node code frequently declares
// its own `const ctx`, and the wrapper must not shadow or collide with it.
async function run(__n8nCtx) {
  __n8nCtx = __n8nCtx || {};
  const $input = __n8nCtx.$input;
  const $ = __n8nCtx.$;
  const $now = __n8nCtx.$now;
  const $json = __n8nCtx.$json;
  const $items = __n8nCtx.$items;
  void $input; void $; void $now; void $json; void $items;
  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`
  // is bound to the context so `this.helpers.*` resolves to the shim's.
  return (async function () {
// ---- BEGIN VERBATIM n8n jsCode ----
// ============================================================================
// INTEGRITY GUARD — fail closed before drafting, approval, state writes or send.
//
// WHY THIS EXISTS. action_id is not unique in the Actions register. 7 ids hold 2
// rows each, and idempotency_key is duplicated on 6 of them, so neither column
// identifies a row. Two independent selection faults follow from that:
//
//   READ vs READ.  Reselect Action If Drafted takes ready[0] (FIRST match) and is
//   authoritative for what gets drafted. Approval Gate takes ahits[length-1]
//   (LAST match) and validates recipient and channel. On ACT-20260101-001-005
//   those are different rows: OBTAIN_REPAIR_QUOTE / "preferred repairer" / MANUAL
//   versus FOLLOW_UP / "Riverside car park/centre management" / GMAIL.
//
//   READ vs WRITE.  Google Sheets appendOrUpdate updates the FIRST match, while
//   almost every reader in this workflow takes the LAST. So a send can be recorded
//   against one row while a different row stays open.
//
// HOW THE GUARD CLOSES BOTH. It does not choose between rows and it does not rank
// them. It refuses to let the branch continue whenever more than one row could be
// selected. When it passes, every in-scope action_id resolves to exactly ONE row,
// so first === last === newest === oldest, and both mismatches become unreachable
// rather than merely unlikely. Containment by elimination, not by arbitration.
//
// It never uses updated_at, created_at, row order or row number to prefer a row.
// Those appear only in the conflict report, so a human can tell the rows apart.
//
// Nothing here writes, approves, drafts, sends or mutates. Read-only.
// ============================================================================

const cfg = $('Config').first().json;
const passthrough = $input.first().json;
const actions = $('Load Actions').all().map(i => i.json).filter(r => r && r.action_id);
const approvals = (() => { try { return $('Load Approvals').all().map(i => i.json).filter(r => r && r.approval_id); }
                           catch (e) { return []; } })();

const S = v => String(v === null || v === undefined ? '' : v).trim();
const U = v => S(v).toUpperCase();

// Content fingerprint. Excludes mutable state (status, updated_at, draft_id,
// approval_id, blocked_reason) so a row stays identifiable across a legal update.
const FP_FIELDS = ['action_id', 'matter_id', 'action_type', 'priority', 'depends_on_json',
  'recipient', 'channel', 'requires_approval', 'idempotency_key', 'created_at'];
function fnv(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return ('00000000' + h.toString(16)).slice(-8);
}
function fingerprint(row) {
  const basis = FP_FIELDS.map(f => S(row[f])).join('|');
  return 'FP-' + fnv(basis) + fnv(basis.split('').reverse().join('') + '|salt2');
}
function rowRef(row, idx) {
  return { snapshot_index: idx, fingerprint: fingerprint(row),
    action_id: S(row.action_id), idempotency_key: S(row.idempotency_key),
    action_type: U(row.action_type), created_at: S(row.created_at) };
}

function halt(code, reason, detail) {
  return [{ json: {
    ...passthrough,
    integrity_ok: false,
    gate: 'DATA_INTEGRITY_CONFLICT',
    integrity_code: code,
    integrity_reason: reason,
    integrity_detail: detail || [],
    // Deliberately absent: any selected row, any winner, any ranking.
  } }];
}

// ---- 1. Establish scope -----------------------------------------------------
// APPROVAL route: the one action the approval names.
// DRAFT route: every action on the matter, because Reselect chooses among them,
// so ambiguity anywhere in that set can change which action is drafted.
const routeGroup = U(cfg.route_group);
let scopeIds = [];
let scopeLabel = '';

if (routeGroup === 'APPROVAL') {
  const aprId = S(cfg.approval_id);
  const hits = approvals.filter(a => S(a.approval_id) === aprId);
  if (!aprId) return halt('NO_APPROVAL_ID', 'The approval route ran without an approval_id.');
  if (!hits.length) return halt('APPROVAL_NOT_FOUND', 'Approval ' + aprId + ' is not on the register.');
  if (hits.length > 1) {
    return halt('DUPLICATE_APPROVAL_ROW',
      'Approval ' + aprId + ' appears on ' + hits.length + ' rows. I will not choose between them.',
      hits.map(h => ({ approval_id: h.approval_id, action_id: h.action_id, draft_id: h.draft_id })));
  }
  scopeIds = [S(hits[0].action_id)];
  scopeLabel = 'approval ' + aprId;
} else {
  const matterId = S(cfg.matter_id);
  if (!matterId) return halt('NO_MATTER_ID', 'No matter_id in scope.');
  const mine = actions.filter(a => S(a.matter_id) === matterId);
  if (!mine.length) return halt('NO_ACTIONS_FOR_MATTER', 'Matter ' + matterId + ' has no action rows.');
  scopeIds = Array.from(new Set(mine.map(a => S(a.action_id))));
  scopeLabel = 'matter ' + matterId;
}

// ---- 2-5. Ambiguity checks. Any one of them stops the branch. ---------------
const conflicts = [];
const selected = {};

// Blank identifiers are themselves ambiguity: they cannot address a row.
actions.filter(a => S(a.matter_id) === S(cfg.matter_id) || scopeIds.indexOf(S(a.action_id)) !== -1)
  .forEach((a, i) => {
    if (!S(a.action_id)) conflicts.push({ code: 'BLANK_ACTION_ID', snapshot_index: i });
    if (!S(a.idempotency_key)) conflicts.push({ code: 'BLANK_IDEMPOTENCY_KEY', action_id: S(a.action_id) });
  });

// 3. Duplicate idempotency_key anywhere in scope, even across different action ids.
const keyIndex = {};
actions.forEach((a, i) => {
  if (scopeIds.indexOf(S(a.action_id)) === -1) return;
  const k = S(a.idempotency_key);
  if (!k) return;
  (keyIndex[k] = keyIndex[k] || []).push(rowRef(a, i));
});
Object.keys(keyIndex).forEach(k => {
  if (keyIndex[k].length > 1) {
    conflicts.push({ code: 'DUPLICATE_IDEMPOTENCY_KEY', idempotency_key: k, rows: keyIndex[k] });
  }
});

// 2 + 4 + 5. Duplicate action_id, and field mismatch between rows sharing one id.
const COMPARE = ['action_type', 'recipient', 'channel', 'requires_approval',
  'depends_on_json', 'idempotency_key', 'matter_id'];

scopeIds.forEach(id => {
  const rows = [];
  actions.forEach((a, i) => { if (S(a.action_id) === id) rows.push({ row: a, ref: rowRef(a, i) }); });

  if (rows.length === 0) {
    conflicts.push({ code: 'ACTION_NOT_FOUND', action_id: id });
    return;
  }
  if (rows.length > 1) {
    const differing = COMPARE.filter(f =>
      Array.from(new Set(rows.map(r => f === 'requires_approval' || f === 'action_type' || f === 'channel'
        ? U(r.row[f]) : S(r.row[f])))).length > 1);
    conflicts.push({
      code: differing.length ? 'DUPLICATE_ACTION_ID_FIELD_MISMATCH' : 'DUPLICATE_ACTION_ID',
      action_id: id,
      row_count: rows.length,
      differing_fields: differing,
      // Candidates listed so a human can tell them apart. Order is register order.
      // It carries no meaning and confers no preference.
      candidates: rows.map(r => r.ref),
    });
    return;
  }
  selected[id] = rows[0].ref;   // exactly one row: first === last, unambiguous
});

// ---- 6. Headline the WORST conflict, and count AMBIGUOUS ACTIONS. ----------
// INCIDENT (harness/FINDINGS.md section 1, reproduced 2026-08-25 by
// node harness/run.js, scenarios wf4-guard-conflicted-action-approval-route (C2)
// and wf4-guard-conflicted-matter-draft-route (C1), both mined from
// hTz7VbLHENx8ZB1N "QA - WF4 Integrity Guard Runtime").
//
// WHAT THE OLD CODE DID.  `const worst = conflicts[0];` -- it took the FIRST
// element of the accumulator and called it the worst. The pushes above happen in
// a fixed statement order (blank action_id, blank idempotency_key, duplicate
// idempotency_key, then per-action_id duplicate / field mismatch), so `worst`
// held whichever class the code happened to push first, not the most serious one.
//
// WHY THAT IS DANGEROUS.  On the real MAT-20260101-002 snapshot every duplicated
// action_id ALSO shares its idempotency_key, so both classes fire. The owner was
// therefore told `DUPLICATE_IDEMPOTENCY_KEY` ("two writes share a key") when the
// truth was `DUPLICATE_ACTION_ID_FIELD_MISMATCH` ("two rows under one action id
// disagree about recipient and channel") -- the condition that could put a
// CONTACT_INSURER letter in front of a car park manager, and the entire reason
// this node exists. integrity_code is carried into Build Integrity Halt Notice
// and shown to the owner verbatim, so the owner was handed the milder of the two.
//
// AND THE COUNT.  The reason string said `conflicts.length` -- 12 on that
// snapshot, against 6 genuinely ambiguous action_ids, because every duplicated id
// is reported once per class. Double the real number of things to fix.
//
// THE FIX. (a) rank by a DECLARED severity order and headline the worst;
// (b) count DISTINCT in-scope action_ids that are implicated, not accumulator
// entries. integrity_detail is still the complete, unreordered list -- nothing is
// dropped, nothing is arbitrated, and Build Integrity Halt Notice sees exactly
// what it saw before. This node still refuses to choose a row; ranking decides
// only which sentence the owner reads first.

// Declared severity, worst first. Ordered by how badly the ambiguity could
// misdirect a real send, NOT by push order and NOT by how many rows it touches.
const CONFLICT_SEVERITY = [
  'DUPLICATE_ACTION_ID_FIELD_MISMATCH', // rows disagree on recipient/channel: wrong party
  'DUPLICATE_IDEMPOTENCY_KEY',          // two writes share a key: wrong row updated
  'DUPLICATE_ACTION_ID',                // same id, same content: still unaddressable
  'BLANK_ACTION_ID',                    // row cannot be addressed at all
  'BLANK_IDEMPOTENCY_KEY',
  'ACTION_NOT_FOUND',
];
function severityRank(code) {
  const i = CONFLICT_SEVERITY.indexOf(String(code));
  return i === -1 ? CONFLICT_SEVERITY.length : i;   // unknown codes rank last
}

if (conflicts.length) {
  // Rank a COPY. conflicts (and therefore integrity_detail) keeps register order,
  // so the halt notice, its MAX_DETAIL slice and its deterministic event_id seed
  // are all byte-for-byte what they were before this fix.
  let worst = conflicts[0];
  for (let i = 1; i < conflicts.length; i++) {
    // Strictly-less-than keeps the earlier push on a tie: stable, so a rerun of
    // the same snapshot always names the same conflict.
    if (severityRank(conflicts[i].code) < severityRank(worst.code)) worst = conflicts[i];
  }

  // Distinct ambiguous action_ids. A DUPLICATE_IDEMPOTENCY_KEY entry can span two
  // different ids, so read its rows too. A BLANK_ACTION_ID entry has no id to
  // count by definition -- it gets a synthetic key so one blank row counts once.
  const ambiguousIds = {};
  conflicts.forEach(c => {
    const id = S(c.action_id);
    if (id) ambiguousIds[id] = true;
    (c.rows || []).forEach(r => { if (S(r.action_id)) ambiguousIds[S(r.action_id)] = true; });
    if (c.code === 'BLANK_ACTION_ID') ambiguousIds['#blank@' + c.snapshot_index] = true;
  });
  const conflictCount = Object.keys(ambiguousIds).length;

  const out = halt(worst.code,
    'More than one Action row could be selected for ' + scopeLabel
    + '. I will not choose between them, and I will not draft, approve, write state or send'
    + ' until a human decides which row is the action. ' + conflictCount
    + ' ambiguous action(s) found, reported as ' + conflicts.length + ' conflict record(s).',
    conflicts);
  // Explicit, so nothing downstream has to infer the number from the length of a
  // list that deliberately reports the same action under more than one class.
  out[0].json.integrity_conflict_count = conflictCount;
  out[0].json.integrity_conflict_record_count = conflicts.length;
  return out;
}

// ---- Unambiguous. Carry the selection forward. ------------------------------
const scopeFingerprint = 'SCOPE-' + fnv(scopeIds.slice().sort()
  .map(id => id + ':' + selected[id].fingerprint).join('|'));

return [{ json: {
  ...passthrough,
  integrity_ok: true,
  integrity_code: 'OK',
  integrity_scope: scopeLabel,
  integrity_scope_ids: scopeIds,
  integrity_scope_fingerprint: scopeFingerprint,
  selected_rows: selected,
  // Convenience for the approval route, where scope is a single action.
  selected_action_id: scopeIds.length === 1 ? scopeIds[0] : '',
  selected_row_fingerprint: scopeIds.length === 1 ? selected[scopeIds[0]].fingerprint : '',
  selected_row_reference: scopeIds.length === 1 ? selected[scopeIds[0]].snapshot_index : -1,
} }];
// ---- END VERBATIM n8n jsCode ----
  }).call(__n8nCtx);
}

module.exports = { run, meta: {
  "workflow": "wf4",
  "nodeName": "Integrity Guard",
  "nodeId": "7bee0e49-ab5e-471d-9a88-4da7d736e459",
  "mode": "runOnceForAllItems",
  "sha256OfJsCode": "039f3be3be2522fd5f38a3941912231cab0f9a348b0ba6a020bac34a374bbe22"
} };
