#!/usr/bin/env python3
"""
extract-units.py -- turn every n8n JavaScript Code node into a standalone JS module.

Reads  : /root/n8n-legal/exports/wf*.json   (scrubbed exports; never modified here)
Writes : /root/n8n-legal/harness/units/<wfN>/<slug>.js
         /root/n8n-legal/harness/units/index.json

The original `parameters.jsCode` is embedded BYTE-IDENTICALLY between the
BEGIN/END markers so a diff against the workflow JSON stays meaningful.
Only a wrapper prologue/epilogue is added around it.
"""

import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORTS = os.path.join(ROOT, "exports")
OUT = os.path.join(ROOT, "harness", "units")

CODE_TYPE = "n8n-nodes-base.code"

BEGIN = "// ---- BEGIN VERBATIM n8n jsCode ----"
END = "// ---- END VERBATIM n8n jsCode ----"


def slugify(name):
    s = name.strip().lower()
    s = s.replace("&", " and ")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-{2,}", "-", s).strip("-")
    return s or "unnamed"


def js_string(value):
    """Safe JS single-line string literal."""
    return json.dumps(value, ensure_ascii=False)


def wrap(js_code, meta):
    """Build the module source. js_code goes in untouched."""
    body = js_code
    if not body.endswith("\n"):
        body += "\n"
    header = (
        "// AUTO-GENERATED by .tooling/extract-units.py -- DO NOT EDIT BY HAND.\n"
        "// Source workflow : %s\n"
        "// Node name       : %s\n"
        "// Node id         : %s\n"
        "// Node mode       : %s\n"
        "// sha256(jsCode)  : %s\n"
        "//\n"
        "// The code between the BEGIN/END markers below is byte-identical to the\n"
        "// node's parameters.jsCode in the workflow export. Everything outside the\n"
        "// markers is harness scaffolding.\n"
        "//\n"
        "// Usage:\n"
        "//   const { makeContext } = require('../../n8n-shim');\n"
        "//   const unit = require('./%s');\n"
        "//   const out = await unit.run(makeContext({ items: [...], nodeOutputs: {...},\n"
        "//                                            now: '2026-01-01T00:00:00.000Z' }));\n"
        "'use strict';\n"
        "\n"
        "// The parameter is deliberately named __n8nCtx: node code frequently declares\n"
        "// its own `const ctx`, and the wrapper must not shadow or collide with it.\n"
        "async function run(__n8nCtx) {\n"
        "  __n8nCtx = __n8nCtx || {};\n"
        "  const $input = __n8nCtx.$input;\n"
        "  const $ = __n8nCtx.$;\n"
        "  const $now = __n8nCtx.$now;\n"
        "  const $json = __n8nCtx.$json;\n"
        "  const $items = __n8nCtx.$items;\n"
        "  void $input; void $; void $now; void $json; void $items;\n"
        "  // Inner async IIFE: n8n Code nodes may use top-level `await`, and `this`\n"
        "  // is bound to the context so `this.helpers.*` resolves to the shim's.\n"
        "  return (async function () {\n"
        % (
            meta["workflow"],
            meta["nodeName"],
            meta["nodeId"],
            meta["mode"],
            meta["sha256OfJsCode"],
            meta["basename"],
        )
    )
    footer = (
        "\n"
        "  }).call(__n8nCtx);\n"
        "}\n"
        "\n"
        "module.exports = { run, meta: %s };\n"
        % json.dumps(
            {k: meta[k] for k in ("workflow", "nodeName", "nodeId", "mode", "sha256OfJsCode")},
            ensure_ascii=False,
            indent=2,
        )
    )
    return header + BEGIN + "\n" + body + END + footer


def main():
    if not os.path.isdir(EXPORTS):
        sys.exit("missing exports dir: %s" % EXPORTS)
    os.makedirs(OUT, exist_ok=True)

    index = []
    per_wf = {}

    files = sorted(
        [f for f in os.listdir(EXPORTS) if re.fullmatch(r"wf\d+\.json", f)],
        key=lambda f: int(re.search(r"\d+", f).group()),
    )
    for fname in files:
        wf = fname[:-5]  # wfN
        with open(os.path.join(EXPORTS, fname), "r", encoding="utf-8") as fh:
            doc = json.load(fh)

        wf_dir = os.path.join(OUT, wf)
        os.makedirs(wf_dir, exist_ok=True)

        seen = {}
        count = 0
        for node in doc.get("nodes", []):
            if node.get("type") != CODE_TYPE:
                continue
            params = node.get("parameters") or {}
            js_code = params.get("jsCode")
            if js_code is None:
                print("  !! %s / %s has no jsCode, skipped" % (wf, node.get("name")))
                continue

            slug = slugify(node.get("name", "unnamed"))
            if slug in seen:
                seen[slug] += 1
                slug = "%s-%d" % (slug, seen[slug])
            else:
                seen[slug] = 1

            sha = hashlib.sha256(js_code.encode("utf-8")).hexdigest()
            meta = {
                "workflow": wf,
                "nodeName": node.get("name"),
                "nodeId": node.get("id"),
                "mode": params.get("mode", "runOnceForAllItems"),
                "sha256OfJsCode": sha,
                "basename": slug,
            }
            rel = os.path.join(wf, slug + ".js")
            path = os.path.join(OUT, rel)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(wrap(js_code, meta))

            index.append(
                {
                    "workflow": wf,
                    "nodeName": meta["nodeName"],
                    "nodeId": meta["nodeId"],
                    "mode": meta["mode"],
                    "file": rel.replace(os.sep, "/"),
                    "bytes": len(js_code.encode("utf-8")),
                    "sha256OfJsCode": sha,
                }
            )
            count += 1
        per_wf[wf] = count

    with open(os.path.join(OUT, "index.json"), "w", encoding="utf-8") as fh:
        json.dump(index, fh, ensure_ascii=False, indent=2)
        fh.write("\n")

    total = 0
    for wf in per_wf:
        print("%-5s %3d units" % (wf, per_wf[wf]))
        total += per_wf[wf]
    print("%-5s %3d units total -> %s" % ("ALL", total, OUT))


if __name__ == "__main__":
    main()
