#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# leak-check.sh -- pre-commit gate. Greps the whole repo for anything that
# looks like a real identifier or a credential and exits non-zero on a hit.
#
#   .tooling/leak-check.sh            # scan the working tree
#   .tooling/leak-check.sh --staged   # scan only files staged for commit
#
# Exit 0 = clean. Exit 1 = at least one pattern matched; the matches are
# printed with file and line. Run this before every commit and before every
# push. If it fires, do NOT add an exception here first -- decide whether the
# string is real. If it is real, add it to .tooling/scrub-map.json and run
# .tooling/scrub.py. Only add an ALLOW entry for a string that is provably
# synthetic, and say why on the same line.
# ---------------------------------------------------------------------------
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

STAGED=0
[[ "${1:-}" == "--staged" ]] && STAGED=1

if [[ $STAGED -eq 1 ]]; then
  mapfile -t FILES < <(git diff --cached --name-only --diff-filter=ACMR)
  [[ ${#FILES[@]} -eq 0 ]] && { echo "leak-check: nothing staged."; exit 0; }
else
  FILES=(.)
fi

EXCLUDES=(--exclude-dir=.git --exclude-dir=node_modules --exclude-dir=__pycache__
          --exclude-dir=.venv --exclude-dir=coverage
          --exclude=leak-check.sh --exclude=scrub-map.json --exclude=.gitignore)

# Line-level allowances: strings that MATCH a pattern below but are provably
# not secrets. sha256OfJsCode / sha256(jsCode) are digests of the node code
# itself; 0x01000193 / 0x811c9dc5 are the FNV-1a prime and offset basis; the
# *_PLACEHOLDER and CRED_* words are the scrubbed replacements.
allow_filter() {
  grep -vE \
    -e 'sha256OfJsCode|sha256\(jsCode\)' \
    -e '0x01000193|0x811c9dc5' \
    -e '(SHEET_ID_PLACEHOLDER|QA_SHEET_ID_PLACEHOLDER|DRIVE_FOLDER_PLACEHOLDER|OWNER_CHAT_ID)' \
    -e 'CRED_(GSHEETS|TELEGRAM|DEEPSEEK|GDRIVE|GMAIL|ANTHROPIC)' \
    -e 'APR-(A1B2C3D4E5F60718|A1B2C3D4000000[0-9]{2})' \
    -e '(MAT|ACT|DRF|COM|EVD)-20260101' \
    -e '^(\./)?exports/wf[0-9]+\.(active|draft)\.json:[0-9]+: *"id": "[0-9]+",?$'
}

# ^ the last allowance: n8n stamps every filter/switch CONDITION with a purely
#   numeric id inside the workflow export. Those are structural, generated by
#   the n8n editor, and are needed to diff against the live instance.
#   The `(\./)?` prefix is load-bearing. Working-tree mode greps `.` so paths come
#   back as `./exports/wf4.active.json`, but --staged feeds git's paths, which have no
#   `./`. An anchor that assumed the dot made --staged fire on 20 of these ids --
#   i.e. the gate failed in precisely the mode you run before a commit.

FAIL=0
hit() {  # hit <label> <extended-regex> [extra grep args...]
  local label="$1"; shift
  local re="$1"; shift
  local out
  out="$(grep -rInE "${EXCLUDES[@]}" "$@" -- "$re" "${FILES[@]}" 2>/dev/null | allow_filter)"
  if [[ -n "$out" ]]; then
    echo "### LEAK: $label"
    echo "$out"
    echo
    FAIL=1
  fi
}

# 1. Known real literals. These must never come back.
# The 6-character prefix, not the full id: a WF1 sticky note wrote the id abbreviated
# as `1L0q0m...UknW`, which the full-string pattern missed entirely on the first pass.
hit "known real spreadsheet id"      '1L0q0m'
hit "known real QA spreadsheet id"   '1oSbh7sQXhrMIdjj75PNSWx2yMUyXY8HNWpbXX0NkeFs'
hit "known real Drive folder id"     '1edaBpb_NGlsJDZLpNuO6gt4vAk6vVCWY'
hit "known real owner chat id"       '\b8507728458\b'
hit "known real credential id"       '(woxaIKDfpe1O59NH|tFIgbbfy2nm79InW|yrENmQuBZMyUl0Bw|4MtfDqGkiTM31mx7|oJhe7heVxU9zVMbf|E43eyEDk0ex0LopI)'
hit "known real matter/action id"    '(MAT-2026(0819|0818|0824|0823|0899|080[123])-[0-9]{3}|ACT-20260819-[0-9]{3}-[0-9]{3})'
hit "known real party / author"      '(Garden City|Ali Rad|\bRAC WA\b|aussieclaims|otherinsurer\.com\.au)'
hit "known real vehicle rego"        '\b1ABC234\b'

# 2. Shape-based. Anything NEW that looks like a Google file id: >=25 chars of
#    [A-Za-z0-9_-] containing upper, lower and a digit. Excludes UUIDs (n8n node
#    and webhook ids, which are deliberately kept) and known placeholder words.
GID="$(grep -rIohE "${EXCLUDES[@]}" -- '[A-Za-z0-9_-]{25,}' "${FILES[@]}" 2>/dev/null \
  | grep -vE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' \
  | grep -vE '[-_]{4,}' \
  | grep -E '[a-z]' | grep -E '[A-Z]' | grep -E '[0-9]' \
  | grep -vE '_' \
  | sort -u)"
if [[ -n "$GID" ]]; then
  echo "### LEAK: google-file-id shaped string(s)"
  echo "$GID" | while read -r g; do
    grep -rInE "${EXCLUDES[@]}" -- "$g" "${FILES[@]}" 2>/dev/null | head -3
  done
  echo
  FAIL=1
fi

# 3. Live-credential shapes.
hit "OpenAI-style key"        'sk-[A-Za-z0-9_-]{16,}'
hit "Google API key"          'AIza[A-Za-z0-9_-]{30,}'
hit "Telegram bot token"      '\b[0-9]{8,12}:[A-Za-z0-9_-]{30,}\b'
hit "Telegram bot path"       '/bot[0-9]{6,}'
hit "Slack token"             'xox[abprs]-[A-Za-z0-9-]{10,}'
hit "AWS access key id"       '\bAKIA[0-9A-Z]{16}\b'
hit "GitHub token"            '\bgh[pousr]_[A-Za-z0-9]{20,}\b'
hit "JWT"                     '\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.'
hit "PEM private key"         'BEGIN [A-Z ]*PRIVATE KEY'

# 4. Assigned secrets: a secret-ish label followed by a literal value.
#    Deliberately narrow so it does not fire on WF9's redaction source, which
#    only ever names these words inside a regex or a comment.
hit "assigned secret value" \
  '(api[_-]?key|apikey|access[_-]?token|refresh[_-]?token|bot[_-]?token|client[_-]?secret|password|passwd|passphrase|authorization)["'"'"']?\s*[:=]\s*["'"'"'][^"'"'"'{$][^"'"'"']{7,}'
hit "bearer literal"          'Bearer\s+[A-Za-z0-9._-]{16,}'

# 5. Real-world identifiers and PII shapes.
hit "long digit run (>=9)"    '(^|[^0-9A-Fa-f._-])[0-9]{9,}([^0-9A-Fa-f._-]|$)'
hit "approval id, real shape" 'APR-[A-F0-9]{8,}'
hit "record id, unexpected"   '\b(EVD|DRF|COM)-2026[0-9]{4,}'
hit "australian mobile"       '(\+?61[ -]?4|\b04)[0-9]{2}[ -]?[0-9]{3}[ -]?[0-9]{3}\b'
hit "australian landline"     '(\+?61[ -]?[2378]|\b0[2378])[ -]?[0-9]{4}[ -]?[0-9]{4}\b'
hit "australian 13/1300/1800" '\b1(3[0-9]{4}|300[ -]?[0-9]{3}[ -]?[0-9]{3}|800[ -]?[0-9]{3}[ -]?[0-9]{3})\b'
hit "street address"          '\b[0-9]+[A-Za-z]? [A-Z][a-z]+ (Street|St|Road|Rd|Avenue|Ave|Drive|Dr|Highway|Hwy|Terrace|Tce|Parade|Pde|Court|Ct|Crescent|Cres|Boulevard|Blvd|Way|Lane|Ln)\b'
hit "AU postcode with state"  '\b(WA|NSW|VIC|QLD|SA|TAS|NT|ACT)[ ,]+[0-9]{4}\b'

# 6. Email addresses outside the reserved / example domains.
EM="$(grep -rIohE "${EXCLUDES[@]}" -- '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}' "${FILES[@]}" 2>/dev/null \
  | grep -viE '@([A-Za-z0-9-]+\.)*(example\.(com|net|org)|example|test|invalid|localhost)$' \
  | grep -viE '@[A-Za-z0-9-]*example[A-Za-z0-9-]*\.(com|net|org|test)$' \
  | sort -u)"
if [[ -n "$EM" ]]; then
  echo "### LEAK: email address outside example./.test reserved domains"
  echo "$EM" | while read -r e; do
    grep -rInE "${EXCLUDES[@]}" -- "$e" "${FILES[@]}" 2>/dev/null | head -3
  done
  echo
  FAIL=1
fi

if [[ $FAIL -ne 0 ]]; then
  echo "leak-check: FAILED. Do not commit."
  echo "Fix by extending .tooling/scrub-map.json and running .tooling/scrub.py,"
  echo "or, only if the string is provably synthetic, by allowing it in allow_filter()."
  exit 1
fi

echo "leak-check: clean."
exit 0
